### ISSUE TITLE
TS.RANGE WITHLABELS?

### ISSUE THREAD

**Issue by vgoklani** [RedisTimeSeries/RedisTimeSeries#1034]
Hey there,

Curious, why doesn't the TS.RANGE function support the WITHLABELS flag? It's in the TS.MRANGE function, but not in TS.RANGE. 

Thanks!

**Comment by LiorKogan** [comment]
`TS.MRANGE` does not have a `key` as a parameter. The result may include multiple time series. To better understand which time series are relevant, or what each of these time series represents - one may need to examine their labels.

`TS.RANGE`, on the other side, is executed on a selected time series, so the query poser is well aware of which time series is it, and may also use `TS.INFO` to examine the labels.

**Comment by vgoklani** [comment]
makes sense, thanks!
