### ISSUE TITLE
redislabs/redistimeseries:1.4.14 was released on 06 Feb 2022, but is not available on dockerhub

### ISSUE THREAD

**Issue by flori** [RedisTimeSeries/RedisTimeSeries#1091]
See

```
$ docker pull redislabs/redistimeseries:1.4.14
Error response from daemon: manifest for redislabs/redistimeseries:1.4.14 not found: manifest unknown: manifest unknown
```

**Comment by gkorland** [comment]
@flori thanks for reporting it out, you're right it seems like there was an issue with the tag. Please notice the latest version is 1.6.9.

**Comment by flori** [comment]
I am trying to use the stable version, but I noticed that some of the 1.6.x "releases" are actually release candidates. How can I depend on a stable version of redistimeseries?

**Comment by LiorKogan** [comment]
RedisTimeSeries 1.6.8 was the first 1.6.x GA (General Availability) release. In other words - "stable", "production ready".

Any following 1.6.x release (x>8) is a maintenance release. In other words - only bug fixes and no new functionality, and is hence "stable" or "production ready" as well.

As of today (16 March 2022) 1.6.9 is the latest release - the one you should use.

**Comment by flori** [comment]
Thank you, I might upgrade to 1.6.9 or higher then.
