### ISSUE TITLE
Unable to run on Ubuntu 20.04 with Redis 5.0.7

### ISSUE THREAD

**Issue by HartS** [RedisTimeSeries/RedisTimeSeries#1099]
I built the redis timeseries module using the steps in the docs (`make setup` and `make build`) in order to run it on Ubuntu 20.04 (the Redis download center only has builds for Ubuntu 16 and 18)

Unfortunately, trying to start Redis with the module fails without anything useful (to me) in the output: https://gist.github.com/HartS/335ffcc016581ef4c06140c0bc5862c8

Starting Redis works without issues when running without `--loadmodule`

I also tried building the module from the `v1.6.8` tag and encountered the same issue

**Comment by HartS** [comment]
I suspect this is related to how the redis is configured through apt install on Ubuntu rather than the timeseries.so build. I have no problem running redis with the timeseries module in a docker container, but when I copy the timeseries.so out of the container and try running redis-server with the module, I get the same failure.

**Comment by gkorland** [comment]
RedisTimeSeries requires Redis 6.0+

**Comment by HartS** [comment]
Thanks @chayim ,  actually got a newer version of redis sorted out, and also saw news of redis-stack, which looks exciting!

I left this issue open as I was thinking of making a PR to add doc notes about the required Redis version (last I checked, this wasn't in the official documentation). However, I haven't gotten around to looking up where in the repo the docs live yet.
