### ISSUE TITLE
Filtering Labels with Comparison Operators

### ISSUE THREAD

**Issue by vgoklani** [RedisTimeSeries/RedisTimeSeries#1117]
Hey there,

Is it possible to add the ability to use comparison operators when filtering by labels. 

To be more specific, Suppose we add this piece of data:

`TS.ADD test * 5 labels gamma 3`

Then a query like this throws an error:

`TS.MRANGE - + FILTER gamma > 2`

Being able to filter numeric labels with comparison operators (i.e. <, >, !=, etc) would be very useful :)

Thanks!

Vishal

**Comment by LiorKogan** [comment]
Hello @vgoklani

Thank you for your suggestion.

This feature would indeed be beneficial for many use cases, however, it would require major changes both in the way we index labels and in the query language itself.

We will consider it in future versions.

**Comment by vgoklani** [comment]
makes sense, thank you for the response @LiorKogan !
