### ISSUE TITLE
Rules do not work on DBs other than 0

### ISSUE THREAD

**Issue by ahmadazizi** [RedisTimeSeries/RedisTimeSeries#1118]
If you create a rule on a timeseries on a DB other than 0 (e.g. 5),  as soon as you add some data, the rule will disappear and never run.

Affected redis versions: all versions
Affected timeseries version: all versions

**Comment by gkorland** [comment]
@ahmadazizi thanks for reporting the bug, but We don't plan to add support to `SELECT` in the near future
Can you please describe your use case?

**Comment by ahmadazizi** [comment]
Thank you, We have separate DBs for each organization, timeseries are organized in their respective DBs.
This is also happening silently, rules cease to exist without any warning and in addiction this type of happening was never mentioned in doc/guides, tending to mislead finding the source of problem.

**Comment by OfirMos** [comment]
Hi @ahmadazizi thanks for reporting the bug, it wasn't reproduced on master or 1.6:

`root@b3444609487c:/data# redis-cli
127.0.0.1:6379> SELECT 1
OK
127.0.0.1:6379[1]> ts.create t1
OK
127.0.0.1:6379[1]> keys *
1) "t1"
127.0.0.1:6379[1]> ts.create t2
OK
127.0.0.1:6379[1]> ts.createrule AGGREGATION sum 10
(error) ERR wrong number of arguments for 'ts.createrule' command
127.0.0.1:6379[1]> ts.createrule t1 t2 AGGREGATION sum 10
OK
127.0.0.1:6379[1]> keys *
1) "t1"
2) "t2"
127.0.0.1:6379[1]> ts.add t1 3 5
(integer) 3
127.0.0.1:6379[1]> ts.add t1 7 8
(integer) 7
127.0.0.1:6379[1]> ts.add t1 15 9
(integer) 15
127.0.0.1:6379[1]> keys *
1) "t1"
2) "t2"
127.0.0.1:6379[1]> ts.range t1 - +
1) 1) (integer) 3
   2) 5
2) 1) (integer) 7
   2) 8
3) 1) (integer) 15
   2) 9
127.0.0.1:6379[1]> ts.range t2 - +
1) 1) (integer) 0
   2) 13`
  
Can you pls share a script that reproduces this bug?

**Comment by ahmadazizi** [comment]
MAKING SURE KEYS DO NOT EXIST WITH THE SAME NAME IN DB0

[5] > select 0
"OK"

> del t1
(integer) 0

> del t2
(integer) 0



> select 2
"OK"

[2] > keys *
(empty list or set)

[2] > ts.create t1
"OK"

[2] > ts.create t2
"OK"

[2] > ts.createrule t1 t2 AGGREGATION MIN 5
"OK"

[2] > ts.info t1
1) "totalSamples"
2) "0"
3) "memoryUsage"
4) "4240"
5) "firstTimestamp"
6) "0"
7) "lastTimestamp"
8) "0"
9) "retentionTime"
10) "0"
11) "chunkCount"
12) "1"
13) "chunkSize"
14) "4096"
15) "chunkType"
16) "compressed"
17) "duplicatePolicy"
18) "null"
19) "labels"
20) (empty list or set)
21) "sourceKey"
22) "null"
23) "rules"
24) 1) 1) "t2"
      2) "5"
      3) "MIN"

[2] > ts.add t1 10 50
(integer) 10

[2] > ts.add t1 5 999
(integer) 5


RULE DOES NOT EXIST AFTER ADDING SAMPLES:

[2] > ts.info t1
1) "totalSamples"
2) "2"
3) "memoryUsage"
4) "4184"
5) "firstTimestamp"
6) "5"
7) "lastTimestamp"
8) "10"
9) "retentionTime"
10) "0"
11) "chunkCount"
12) "1"
13) "chunkSize"
14) "4096"
15) "chunkType"
16) "compressed"
17) "duplicatePolicy"
18) "null"
19) "labels"
20) (empty list or set)
21) "sourceKey"
22) "null"
23) "rules"
24) (empty list or set)

[2] > ts.range t2 - +
(empty list or set)

THIS DOES NOT HAPPEN IN DB0

**Comment by LiorKogan** [comment]
Related: https://stackoverflow.com/questions/72116930/redisearch-cannot-create-index-on-db-0
