### ISSUE TITLE
Optimal choices for ENCODING and CHUNK_SIZE ?

### ISSUE THREAD

**Issue by vgoklani** [RedisTimeSeries/RedisTimeSeries#1123]
Hello,

How should we set the ENCODING and CHUNK_SIZE, what should the thought process be? 

In particular, should these choices depend on the length/sparsity of the time-series? Some are more frequently updated than others, should we then change the choice of CHUNK_SIZE? It's not clear to me how to tune these two parameters.

I really *love* redistimeseries - especially the Grafana integration, but it's eating a lot of RAM and we need to somehow optimize/tune it.

Thank you!

**Comment by vgoklani** [comment]
Hey @LiorKogan 

Our data is inserted sequentially, so we don't have any out-of-order insertions issues.

My question is more about initialization of the redis keys, and optimizing memory usage and performance as the keys are appended sequentially.

Thanks,

Vishal

**Comment by LiorKogan** [comment]
The data in each key is stored in chunks. Each chunk contains data in a given timeframe. The default chunk size is 4K bytes (a single memory page).

We keep an index of all chucks. Then, inside each chunk - we iterate.

There are tradeoffs for having smaller or larger sizes of chunks, and it depends on your usage:

* Insert performance: Smaller chunks result in slower inserts (more chunks need to be created).
* Query performance: Queries for a small subset when the chunks are very large - are slower, as we need to iterate over the chunk to find the data.

If you are unsure about your use case, you should stick with the default. Also, if you don’t have a lot of samples per key, having a smaller chunk would benefit you more (space-wise, you can go down to 256).

As for encoding - COMPRESSED (explained [here](https://redis.com/blog/redistimeseries-version-1-2-is-here/)) is almost always the right choice. You will usually gain about 90% memory reduction with minimal processing overhead. The exception may be highly irregular (almost random) timestamps or values, which is rarely the case.

**Comment by vgoklani** [comment]
Thank you @LiorKogan that was very helpful!
