### ISSUE TITLE
Can Redis opensource be used as database in production 

### ISSUE THREAD

**Issue by SurKanchi** [RedisTimeSeries/RedisTimeSeries#1126]
I need simple answer whether can i use redis community edition opensource as a backend database in our microservice for production deployment. 
I have a confusion after reading this "If your application built with RSAL-protected software is NOT a database product, RSAL defines it as “your application,”

**Comment by LiorKogan** [comment]
RSAL has clear definitions of _Your Application_ and _Database Product_. I'm not sure which term is not clear.

If you have any doubt, you should consult with your company's legal team. We can refer them to Redis' legal team if needed.
