### ISSUE TITLE
Potential memory leak in TSDB_queryindex and TSDB_mrange

### ISSUE THREAD

**Issue by danni-m** [RedisTimeSeries/RedisTimeSeries#113]
Both function use `parseLabelListFromArgs` which uses malloc to allocate the strings, those strings are not released since we allocate in `_parseLabel` using RedisModule_CreateString and ctx==NULL.

**Comment by K-Jo** [comment]
relates to #45 and #46

**Comment by gkorland** [comment]
@danni-m Is it still relevant?

**Comment by danni-m** [comment]
@gkorland yes

**Comment by danni-m** [comment]
This was fixed as part of @otnielvh PR with the list matching
