### ISSUE TITLE
timeseries.refreshcluster

### ISSUE THREAD

**Issue by seunghx** [RedisTimeSeries/RedisTimeSeries#1171]
hi
I'm using redis ts with redis cluster. 
Sometimes. ts.mrange result were not consistent
at this time, im solving this issues by calling series.refreshcluster command for all nodes of clusters.

More automatically and actively, I want to address this data inconsistency issues above. 

When exactly should I call this command(timeseries.refreshcluster)?
and I didn't find the code for the command, is there a link?

**Comment by seunghx** [comment]
@MeirShpilraien 
thanks for kind answer
so, when i call this command?

Can i know exactly the meaning of the topology changes? 
Is it only when the node is added/deleted to cluster? or even when the master/slave has been changed?

**Comment by MeirShpilraien** [comment]
node added/deleted and primary/replica role changes.
