### ISSUE TITLE
`DUPLICATE_POLICY` Clarification Required

### ISSUE THREAD

**Issue by ayushsharma82** [RedisTimeSeries/RedisTimeSeries#1219]
Hi,

Thanks for the work on this module! It's much appreciated. I have a question regarding `DUPLICATE_POLICY` [here](https://redis.io/commands/ts.create/).

Does this policy apply globally to a timeseries or are duplicate timestamps allowed when the labels differ? 

_For example:_ I've 2 sensors with unique sensor ID that will report back to redis timeseries. In case these 2 sensors report back samples at the same unix timestamp but with different labels ( sensor id label ), will any one of these samples be blocked?

**Comment by LiorKogan** [comment]
> Does this policy apply globally to a timeseries or are duplicate timestamps allowed when the labels differ?

Let me clarify something: labels apply to a time series, not to a sample. A policy applies to a time series, regardless of labels. Each time series is identified by its key.

> For example: I've 2 sensors with unique sensor ID that will report back to redis timeseries. In case these 2 sensors report back samples at the same unix timestamp but with different labels ( sensor id label ), will any one of these samples be blocked?

If you store each sensor in its own time series, this question is irrelevant. Each time series manages separately and can have different labels as well as a different policy.

**Comment by ayushsharma82** [comment]
Hi @LiorKogan , Thanks a lot for the clarifying my doubts.

Well, that sorts it out. So I'll create separate time series for each sensor. 

Q: Do you know if multi field-value samples will ever be supported or is this something in the works? This is specially important for IoT monitoring where even a tiny sensor will report back 8+ different metrics.

Lastly, Is there any performance drawback with using secondary indexes?

**Comment by LiorKogan** [comment]
> Do you know if multi field-value samples will ever be supported or is this something in the works?

The answer is yes, but there is no more public information I can share right now.

> Is there any performance drawback with using secondary indexes?

No, there are no performance drawbacks. The usage of labels is highly optimized and you can add many labels to each time series to implement a multi-dimensional indexing.

**Comment by ayushsharma82** [comment]
@LiorKogan  Awesome. Thanks for taking your time to answer my questions! 😄
