### ISSUE TITLE
Keeping entries with duplicate timestamps 

### ISSUE THREAD

**Issue by hakeemo** [RedisTimeSeries/RedisTimeSeries#1229]
Looking at the possible DUPLICATE_POLICY choices, there seems to be no way of keeping entries with duplicate timestamps. Is this currently the case?

**Comment by LiorKogan** [comment]
This is correct.

A Redis time series is designed to hold measurements of a single metric - e.g. the temperature reported by a given sensor, or the price of a given stock. The phenomena being measured has only one value at any given timestamp.
