### ISSUE TITLE
Add Versioning to command documentation

### ISSUE THREAD

**Issue by stockholmux** [RedisTimeSeries/RedisTimeSeries#126]
Many of the commands in the documentation are not available when running the module in Docker. There should be some indication that, say, `TS.ALTER` or `TS.MGET` are only available in the master branch.

**Comment by danni-m** [comment]
@stockholmux which docker image are you using?

**Comment by stockholmux** [comment]
```
> module list
1) 1) "name"
   2) "timeseries"
   3) "ver"
   4) (integer) 200
```

**Comment by K-Jo** [comment]
@stockholmux as RedisTimeSeries is not GA yet, we don't plan the documentation to align with several versions.  Once this is the case, we'll add when new commands are added.

**Comment by stockholmux** [comment]
You should do _something_ to warn someone that documentation will not align. It's a frustrating experience to try out the software otherwise.
