### ISSUE TITLE
"Enabled diskless replication"

### ISSUE THREAD

**Issue by vgoklani** [RedisTimeSeries/RedisTimeSeries#1281]
Not sure what happened, but my redistimeseries instance stopped writing to disk.  Please help!

I see this when the redis instance starts up:

```
1:C 11 Sep 2022 16:02:16.891 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Sep 2022 16:02:16.892 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Sep 2022 16:02:16.892 # Configuration loaded
1:M 11 Sep 2022 16:02:16.893 * monotonic clock: POSIX clock_gettime
1:M 11 Sep 2022 16:02:16.893 * Running mode=standalone, port=6379.
1:M 11 Sep 2022 16:02:16.893 # Server initialized
1:M 11 Sep 2022 16:02:16.894 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 11 Sep 2022 16:02:16.895 * <timeseries> RedisTimeSeries version 10617, git_sha=c32b0cb0d8ebc1d31b74c624b8b0424628ff7887
1:M 11 Sep 2022 16:02:16.895 * <timeseries> Redis version found by RedisTimeSeries : 6.2.6 - oss
1:M 11 Sep 2022 16:02:16.895 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
1:M 11 Sep 2022 16:02:16.895 * <timeseries> loaded server DUPLICATE_POLICY: block
1:M 11 Sep 2022 16:02:16.895 * <timeseries> Setting default series ENCODING to: compressed
1:M 11 Sep 2022 16:02:16.895 * <timeseries> Detected redis oss
1:M 11 Sep 2022 16:02:16.896 * <timeseries> Enabled diskless replication
1:M 11 Sep 2022 16:02:16.896 * Module 'timeseries' loaded from /usr/lib/redis/modules/redistimeseries.so
1:M 11 Sep 2022 16:02:16.896 * Ready to accept connections
```

Why does it say:

`Enabled diskless replication`

I'm running this via docker-compose, and this is the relevant portion of my config file:

    redis0:
      restart: always
      image: redislabs/redistimeseries:latest
      ports:
        - "127.0.0.1:6379:6379"
      volumes:
        - ${OPT_DOCKER_DIRECTORY}/data/redis0:/data
      mem_limit: 32768m
      env_file:
        - ./environment
      container_name: redis0
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 120s
        timeout: 5s
        retries: 3
        start_period: 15s
      # save <seconds> <changes> [<seconds> <changes> ...]
      # 10min 1 change | 5min 10 changes | 1min 100 changes
      command: ["redis-server", "--port 6379", "--appendonly yes", "--appendfsync everysec", "--appendfilename appendonly.aof", "--dbfilename redis.rdb", "--save 600 1 300 10 60 100", "--dir /data", "--protected-mode yes", "--bind 0.0.0.0", "--requirepass ${REDIS_PASSWORD}", "--loadmodule /usr/lib/redis/modules/redistimeseries.so", "RETENTION_POLICY 0", "DUPLICATE_POLICY SUM"]

All the data is now lost when I reboot the server. 

Please help!

**Comment by LiorKogan** [comment]
@vgoklani did you find the root cause?

**Comment by vgoklani** [comment]
Hey @LiorKogan thanks for following up!

It's not clear why it stopped writing to the RDB database; I've enabled both the AOF and the RDB persistence options in the docker-compose file (see above)

I see the AOF files, but the RDB files are not getting created. I'm using this for the save criteria: 

    --save 600 1 300 10 60 100

as a temporary workaround, I'm calling bg_save every hour.
