### ISSUE TITLE
MRANGE segmentation fault with empty label list

### ISSUE THREAD

**Issue by gacha** [RedisTimeSeries/RedisTimeSeries#132]
On latest master at time of writing:
`TS.MRANGE 1560526942 1560627260 FILTER test=()`
results in segmentation fault, probably should be a syntax error.

Thanks in advance.

**Comment by itamarhaber** [comment]
Hello @gacha 

Thanks for taking this for a ride and even more so for reporting this issue - looks like a trivial check is missing ;)
