### ISSUE TITLE
Loading module crash (bug report)

### ISSUE THREAD

**Issue by stdcout42** [RedisTimeSeries/RedisTimeSeries#1330]
OS: Ubuntu focal

Running locally, after following the [guide](https://redis.io/docs/stack/timeseries/quickstart/), and successfully  make/building and attempting to load the timeseries module with: `loadmodule /etc/redis/RedisTimeSeries/bin/linux-x64-release/redistimeseries.so` placed in `redis.conf` -- I get the following bug report dump:

[bug_dump_redis.txt](https://github.com/RedisTimeSeries/RedisTimeSeries/files/9888452/bug_dump_redis.txt)

**Comment by LiorKogan** [comment]
RedisTimeSeries 1.8 requires minimal Redis version 6.0.
It is recommended that you update to 6.2
