### ISSUE TITLE
What does it mean "In your redis-server run: loadmodule bin/redistimeseries.so"?

### ISSUE THREAD

**Issue by oprogramador** [RedisTimeSeries/RedisTimeSeries#1332]
I can see `In your redis-server run: loadmodule bin/redistimeseries.so` in the README.

I'm not sure what it means exactly.

I added `loadmodule bin/redistimeseries.so` to the `redis.conf` file and restarted the redis server but still the module isn't loaded.

```
127.0.0.1:6379> TS.ADD
(error) ERR unknown command 'TS.ADD', with args beginning with:
127.0.0.1:6379> MODULE LIST
(empty array)
```

I cannot load the module from the redis client either though I've written `enable-module-command local` in the the `redis.conf` file.
```
127.0.0.1:6379> MODULE LOAD bin/redistimeseries.so
(error) ERR MODULE command not allowed. If the enable-module-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
```

**Comment by oprogramador** [comment]
This plugin worked with `docker run -p 6379:6379 --name redis-stack redis/redis-stack:latest`.

**Comment by LiorKogan** [comment]
> I added loadmodule bin/redistimeseries.so to the redis.conf file and restarted the redis server but still the module isn't loaded.

Is redistimeseires.so located in that folder? Try pointing to an absolute folder. It should work when the file is available.

> I cannot load the module from the redis client either though I've written enable-module-command local in the the redis.conf file.

Make sure you replace the line
```
# enable-module-command no
```
with
```
enable-module-command local
```

and load redis-server with
```
redis-server redis.conf
```

**Comment by oprogramador** [comment]
Thanks for your help.

I don't need it any longer, and I don't have enough time to check that so I close this issue.
