### ISSUE TITLE
Module failed to parse multiple argument compaction

### ISSUE THREAD

**Issue by kramik1** [RedisTimeSeries/RedisTimeSeries#1354]
I am trying to set default arguments for TS creation. Using the examples in the documentation I tried to run this within a conf file. I am on the 1.8.3 tag.

From documentation page: https://redis.io/docs/stack/timeseries/configuration/
```sh
$ redis-server --loadmodule ./redistimeseries.so COMPACTION_POLICY max:1m:1h;min:10s:5d:10d;last:5M:10ms;avg:2h:10d;avg:3d:100d
```

It only seems to work with one argument "ie COMPACTION_POLICY max:1m:1h"

**Comment by LiorKogan** [comment]
Hey @kramik1 thank you for reporting.
I just notice the the example includes the term `10ms` which is invalid.
We will check it further and fix tomorrow.

**Comment by LiorKogan** [comment]
@kramik1 

Yes, this was just a bad example which we fixed.
