### ISSUE TITLE
DUPLICATE_POLICY FIRST causing TS data to only contain 1 sample

### ISSUE THREAD

**Issue by kramik1** [RedisTimeSeries/RedisTimeSeries#1363]
So I am writing a redis output plug-in for fluent-bit for metric data. I noticed in my testing that when I have a module level policy for DUPLICATE_POLICY FIRST that it is only keeping one sample, the last one inserted. When I removed the policy, it worked fine. I also ran a python program at the sametime to send random TS data where I specify the aggregation rules, and it worked as expected. When I would try to insert data using the CLI at the sametime it would also return that the retention time for the key already expired. I have the retention set for 12 hours and the timestamp was only minutes old. 

This is my module compaction policy COMPACTION_POLICY avg:1h:10d:0M RETENTION_POLICY 43200000 DUPLICATE_POLICY FIRST

I ran into an issue a couple of weeks ago where the redis connection would die if I inserted data too quickly with duplicate policy first. Updating the library to the latest version resolved the problem. 

I will try and make a small program to reproduce this problem. Should I avoid using the module level policy. It seems to work better if the policy is setup during runtime.

**Comment by OfirMos** [comment]
Hi @kramik1,
I wasn't able to reproduce this on 1.8
Can you pls prepare small reproduction script?
P.S: which version did you used when you noticed the  DUPLICATE_POLICY FIRST bug?
Thanks!

**Comment by kramik1** [comment]
I am on the 1.8.3 branch. I will work on making this a reproducible smaller executable.

**Comment by kramik1** [comment]
So I am going to close this since I have moved onto relying on specific rule per series and building features into the application to handle that. I was on the head for the 1.8 branch which has now been released with 1.8.3 and now on 1.8.10. I was on 1.8.2 beta head. Reproducing this would be a lot of work for not a lot of squeeze.
