### ISSUE TITLE
Retention and Delete not working

### ISSUE THREAD

**Issue by nick-reinstein** [RedisTimeSeries/RedisTimeSeries#1395]
I am unable to remove elements from a RedisTimeSeries.  I have tried via retention and via explicitly deleting a range and neither work.

I have included the retention_msecs parameter in add() and create() and alter() functions.  I have messed with the value (the amount of milliseconds).  I have checked that the values are correct.  I have made sure to add an element to the series so I can verify the element is still present or not.

After successfully creating a series and successfully adding to it, I expect values to eventually be removed once new entries are added but that is not what im witnessing.
Because values are never being removed the series just keeps growing and I will eventually run out of memory.

Because redis=py is mentioned on the redis site and this is an official module, I kind of expect core functionality to work but it doesn't seem to.  I am not sure if this is because I am operating in WSL2 or not but all other redis features appear to be working in WSL2.

My code is in 2 programs (they run on distinct servers) and kind of hard to paste all of the code as plenty of other functionality is intertwined, but I am able to add to and view the elements, I am just unable to remove any of them using any method I can find in the documentation.

I cannot use RedisTimeSeries with this bug.

I have 2 years of redis experience in C++ using redis-plus-plus on another system and I have been able to use redis-py in other ways across this project.

**Comment by nick-reinstein** [comment]
I don't think this functionality is working well, I don't think it is well documented. and I don't think the library provides adequate feedback.  I am going to just load this data from the database as this wasn't meant to be so difficult to work with.

**Comment by LiorKogan** [comment]
@nick-reinstein can you please provide a minimal code / set of Redis commands that demonstrates the problem the you experienced?

**Comment by nick-reinstein** [comment]
I am giving up on using this feature and probably this library.  I have to write too much code to manage the removal of unwanted elements (due to time) because of how this library works.  I am just storing a series of values using given timestamps (instead of server-captured timestamps using "*") and I want the records within 100 minutes of "now" but wont be able to add a bogus record just so ts.range() doen't return obsolete records (i am baffled by this design choice).

I can use redis-cli commands and see at a high level what redis is doing, but I cannot evaluate when the objects should be cleared or not from what is stored in redis with my data set so I'll just make something else.

**Comment by nick-reinstein** [comment]
I got it to clear off old records but not correctly.  I made sure that the values were converted to local time where redis-server is running and now see they are clearing...

However, they are clearing after around 10 minutes with a retention_msecs value of 100 minutes (100*60*1000).

Any idea why that would be?
