### ISSUE TITLE
Does timeseries support persistence?

### ISSUE THREAD

**Issue by Matteturtle09** [RedisTimeSeries/RedisTimeSeries#1408]
How to use persistence in docker redis stack server?

**Comment by LiorKogan** [comment]
Yes, data can be persisted like any other Redis data structure.
For the docker image this is the default behavior. You can stop an image an start it again - you won't loose your data.

**Comment by Matteturtle09** [comment]
>Thanks for the answer.
Now i have another problem, i can't use conf files with redis stack on docker.
When i use config rewrite i get an error saying " the server is running without a config file ".

**Comment by LiorKogan** [comment]
The `redis-stack-server` Docker image (as well as all other Redis Docker images) is intended to run as-is, please don't try to tweak it.

**Comment by Matteturtle09** [comment]
I want to set appendonly to yes and change the save interval to 60 seconds if 1 change

**Comment by Matteturtle09** [comment]
I need to save the database every 60 seconds, how can i do?
