### ISSUE TITLE
occurs error in make source code

### ISSUE THREAD

**Issue by Jiangchh** [RedisTimeSeries/RedisTimeSeries#1419]
it's my first time to use redistimeseries,i'm having the following issue

my command : docker run --rm -v F:\\git_cache\\RedisTimeSeries:/usr/src/redis-timeseries -w /usr/src/redis-timeseries grokzen/redis-cluster:latest make 

console show: Makefile:231: /rules: No such file or directory
make: *** No rule to make target '/rules'.  Stop.

if i modify the makefile :#include $(MK)/rules
then show: Makefile:179: /defs: No such file or directory
make: *** No rule to make target '/defs'.  Stop.

how to fix it?

**Comment by LiorKogan** [comment]
Why not simply `docker run redislabs/redistimeseries:latest`?

**Comment by Jiangchh** [comment]
sorry, maybe i didn't describe clearly.
i want to experice the installation procedure of  RedisTimeSeries on redis-cluster,no matter which container.
because in my company ,i have to install the module on linux machine online.
so i must know all the problems in installing  or using the RedisTimeSeries by myself.
