### ISSUE TITLE
How to upgrade from v1.4.10 to the latest version without losing data?

### ISSUE THREAD

**Issue by atwoz** [RedisTimeSeries/RedisTimeSeries#1433]
Where can I find the steps to upgrade from v1.4.10 to the latest version (1.8.x) without losing data? I can handle a down time of some minutes but I need to keep the current data.

**Comment by LiorKogan** [comment]
Which Redis version are you using?
Single instance or cluster?

**Comment by atwoz** [comment]
Redis Version: 6.0.8
Single Instance

Probably would also be a good idea to upgrade to redis 7 but it all depends on the complexity.

Thanks Lior.

**Comment by atwoz** [comment]
Thanks Lior, will try that.
