### ISSUE TITLE
[BUG] Visualizer shows dates 50 years in the past

### ISSUE THREAD

**Issue by W-Lawless** [RedisTimeSeries/RedisTimeSeries#1448]
Hello, 

I am doing some initial experiments into using Redis Time Series, and am ingesting some simple data using 

github.com/xtordoir/goanda/api
github.com/RedisTimeSeries/redistimeseries-go

To fetch some simple candle data and place it into a series. 

I cannot find any error in my implementation. 

```
Adding 1.08393  @  1680008400
1680008400
Adding 1.08283  @  1680010200
1680010200
Adding 1.08244  @  1680012000
1680012000
Adding 1.08264  @  1680013800
1680013800
Adding 1.08322  @  1680015600
1680015600
```

Is my console output corresponding to 

```
	fmt.Println("Adding", candleData.Mid.O, " @ ", timestamp)
	savedAt, err := client.Add(keyname+":open", timestamp, candleData.Mid.O)
	if err == nil {
		fmt.Println(savedAt)
	}
```

Using the epoch converter, these dates are correct.

However when I run `TS.RANGE EUR_USD:open - + FILTER_BY_VALUE 0 10`

<img width="966" alt="Screen Shot 2023-03-28 at 11 04 25 AM" src="https://user-images.githubusercontent.com/56946706/228281980-73b980ae-83f7-49c9-a91c-cb326d9fd2dc.png">

I cannot understand why the visualizer says my data is in 1970 except that it is a bug.

**Comment by LiorKogan** [comment]
@W-Lawless can you switch to text-mode and share the query results?
![image](https://user-images.githubusercontent.com/7252991/228328426-2a03e0ea-0f8f-4a40-b544-0f03876b9329.png)

**Comment by W-Lawless** [comment]
> @W-Lawless you are using timestamps in seconds instead of milliseconds.

Ah. Rookie mistake. When I was staring at the epoch converter and watching the clock tick maybe I should've clued in. I had assumed the Go time library would give me millisecond when calling .Unix, but I guess I have to manually * 1000

**Comment by W-Lawless** [comment]
> @W-Lawless you are using timestamps in seconds instead of milliseconds.

Ah. Rookie mistake. When I was staring at the epoch converter and watching the clock tick maybe I should've clued in. I had assumed the Go time library would give me millisecond when calling .Unix, but I guess I have to manually * 1000
