### ISSUE TITLE
Docker container has THP enabled

### ISSUE THREAD

**Issue by banker** [RedisTimeSeries/RedisTimeSeries#146]
When you run docker run -p 6379:6379 -it --rm redislabs/redistimeseries

The Redis server is showing this warning:

1:M 21 Jun 2019 18:42:12.791 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

This causes major performance issues. Can we remove?

**Comment by itamarhaber** [comment]
Hello @banker 

No - this is a host setting, not a container's, refer to https://github.com/docker-library/redis/issues/55#issuecomment-214872432 (among others).
