### ISSUE TITLE
Feature Request: Get closest value to timestamp (TS.GET key [CLOSEST timestamp [-|+]])

### ISSUE THREAD

**Issue by jamesastound** [RedisTimeSeries/RedisTimeSeries#1464]
Example time series data:

```
[
  { timestamp: 1, value: 4232}
  { timestamp: 2, value: 6434}
  { timestamp: 6, value: 143}
  { timestamp: 8, value: 6575}
]
```

Example query 1:
`TS.GET key CLOSEST 3 -`

The example would return the value (or timestamp/value), where timestamp = 2, being the closest existing timestamp to the query (3). The query timestamp is not the median so `[-|+]` is ignored.
Query 1 Result: `6434`

Example query 2:
`TS.GET key CLOSEST 7 +`

The example would return the value, where timestamp = 8, because 7 is the median of 6 and 8, but the `[-|+]` indicates it choses the greater timestamp value.
Query 2 Result: `6575`

- `[-|+]` should probably be required instead of having a default
- If query timestamp is greater or equal to the most recent, return the most recent value.
- If query timestamp is less than or equal to the earliest timestamp, return the earliest timestamp value

Thank you for the consideration.

**Comment by LiorKogan** [comment]
What you suggested is already supported when `-` or `+` are specified:

-  `TS.GET key CLOSEST 7 -` can already be executed with `TS.RANGE key 0 7 AGGREGATION LAST 7`
-  `TS.GET key CLOSEST 7 +` can already be executed with `TS.RANGE key 7 + ALIGN 7 AGGREGATION FIRST 9199999999999999999`

**Comment by jamesastound** [comment]
Thanks. You're welcome to close this request if you feel it's not worth having a separate command.
