### ISSUE TITLE
TS.Mrange slow when filter contain list of values

### ISSUE THREAD

**Issue by kszarlej** [RedisTimeSeries/RedisTimeSeries#1476]
Hello. I have the following Mrange query with the following filters:

``` 
[
    account_id=0e732b33-2ec3-4789-871a-54dcc9ee4e5d 
    metric_name=my_test_metric
    location=(EU-1)
    monitor_uuid=(b8171a40-4b56-4a6d-935d-0b9e041b3e54)
]
```

The location filter matches only against a single location EU-1. This query executes very fast, in a matter of microseconds.

```
{"level":"info","time":"2023-06-16T14:29:11Z","message":"time it took to query redis: 540.546µs"}
```

However, when I only add another location like below

```
[
    account_id=0e732b33-2ec3-4789-871a-54dcc9ee4e5d
    metric_name=my_test_metric
    location=(EU-1,NA-1)
    monitor_uuid=(b8171a40-4b56-4a6d-935d-0b9e041b3e54)
]
```

The query slows down 200 times (it takes now around 100 milliseconds)

```
 {"level":"info","time":"2023-06-16T14:29:21Z","message":"time it took to query redis: 111.16136ms"}
```

Technically one solution is to run two Mranges for each location and then join the results in the client but this seems suboptimal.

Is there a way to speed up the queries whose filters contains list of values?

Best Regards!

**Comment by LiorKogan** [comment]
Fixed in RedisTimeSeries 1.8.11
