### ISSUE TITLE
TS.RANGE BUCKETTIMESTAMP option at 'low' or 'high' causes fatal error

### ISSUE THREAD

**Issue by WolfWFr** [RedisTimeSeries/RedisTimeSeries#1494]
We are running redis v2.6.2 with redis-timeseries v1.8.10 and are running into an issue with regard to the `BUCKETTIMESTAMP` option of the `TS.RANGE` command.

When using `BUCKETTIMESTAMP` `high` or `low`, the server closes the connection.
When using `BUCKETTIMESTAMP` `-`, `+`, `~`, or `mid` the server returns the expected response.

I followed the documentation at:
https://redis.io/commands/ts.range/

Example query:
```
ts.range my_redis_key 1688996093000 1689082493000  AGGREGATION avg 1200000 BUCKETTIMESTAMP high
```

Looking at the documentation and the fact that the `mid` value seems to work, this seems to be a bug.

For us this isn't a pressing concern, I just wanted to provide the feedback.

**Comment by LiorKogan** [comment]
@WolfWFr thank you for the report

I can see that there are two issues here:
1. We need to fix our documentation: it should be `start` and `end` instead of `low` and `high`
2. We are missing an internal check when the parsing fails. This is something we should fix.

**Comment by WolfWFr** [comment]
@LiorKogan Thank you for the quick reply, I'm happy I could help.

**Comment by OfirMos** [comment]
This is the fix PR:
https://github.com/RedisTimeSeries/RedisTimeSeries/pull/1496
