### ISSUE TITLE
same key label is regular feature?

### ISSUE THREAD

**Issue by luasenvy** [RedisTimeSeries/RedisTimeSeries#1564]
hi, i wonder is ok using same key label like hashtag.
e.g.) `TS.CREATE program:language:html labels hashtag language hashtag program hashtag html hashtag markdown`

next is `ts.info` one of key with facilityId label include `OZGQeoUByfs7UKSMh4xG`.:
![image](https://github.com/RedisTimeSeries/RedisTimeSeries/assets/24634713/62af50aa-41a7-42b0-94ea-95df4f84864c)

---

a lot of key is exists facilityId Is `OZGQeoUByfs7UKSMh4xG`.
all key has label `facilityId=OZGQeoUByfs7UKSMh4xG` in next result. but some key is one or more `facilityId` labeled.
 
![image](https://github.com/RedisTimeSeries/RedisTimeSeries/assets/24634713/00fb2342-461b-4697-907b-176355f1dd17)

and i queried with `TS.QUERYINDEX facilityId=tMQBnXFHl8CUd4z1ADLo facilityId=OZGQeoUByfs7UKSMh4xG type=raw`.

![image](https://github.com/RedisTimeSeries/RedisTimeSeries/assets/24634713/23143f0e-0be3-4931-bcd4-eb20d8844629)

result is working with `AND` clause with `labels`:
![image](https://github.com/RedisTimeSeries/RedisTimeSeries/assets/24634713/d6fd859a-83d0-440c-bfb3-0eabd7e56f97)

so i think multiple value label search is working correct like `hashtag` search.

---

but, i using ts.mrange with groupby the same key label. result is seems like ignore after first `facilityId` label.
because `OZGQeoUByfs7UKSMh4xG` label data is not exists:

`TS.MRANGE - + WITHLABELS FILTER facilityId=OZGQeoUByfs7UKSMh4xG type=raw GROUPBY facilityId REDUCE sum`
 
![image](https://github.com/RedisTimeSeries/RedisTimeSeries/assets/24634713/c4fd56c1-3ddc-4802-a664-7c92c7b75b4a)

if i using redis timeseries incorrect way, please reply me. i will found other way.

thank you.

**Comment by LiorKogan** [comment]
I'm not sure I understand the problem you are describing. I tried the following:

```
redis> TS.CREATE t LABELS x 1 x 2 y 3
redis> TS.ADD t 1 1
redis >TS.MRANGE - + FILTER x=1 x=2 y=3 GROUPBY y REDUCE sum
1) 1) "y=3"
   2) (empty array)
   3) 1) 1) (integer) 1
         2) 1
```

As expected.

When grouping by a LABEL that has multiple values:

```
redis >TS.MRANGE - + FILTER x=1 x=2 y=3 GROUPBY x REDUCE sum
1) 1) "x=1"
   2) (empty array)
   3) 1) 1) (integer) 1
         2) 1
```

you can see that filtering works as expected, but the `GROUPBY x` splits by the first value encountered.

Let's add 2 more time series:

```
redis> TS.CREATE t2 LABELS x 1 y 3
redis> TS.ADD t2 1 1
redis> TS.CREATE t3 LABELS x 2 y 3
redis> TS.ADD t3 1 1

redis> TS.MRANGE - + WITHLABELS FILTER x=2 y=3 GROUPBY x REDUCE sum
1) 1) "x=1"
   2) 1) 1) "x"
         2) "1"
      2) 1) "__reducer__"
         2) "sum"
      3) 1) "__source__"
         2) "t"
   3) 1) 1) (integer) 1
         2) 1
2) 1) "x=2"
   2) 1) 1) "x"
         2) "2"
      2) 1) "__reducer__"
         2) "sum"
      3) 1) "__source__"
         2) "t3"
   3) 1) 1) (integer) 1
         2) 1
```         

Again, the results are correct: only time series with `x=2` are considered (t, t3), but the `GROUPBY x` splits by the first value encountered. 

Same here:

```
redis> TS.MRANGE - + WITHLABELS FILTER y=3 GROUPBY x REDUCE sum
1) 1) "x=1"
   2) 1) 1) "x"
         2) "1"
      2) 1) "__reducer__"
         2) "sum"
      3) 1) "__source__"
         2) "t,t2"
   3) 1) 1) (integer) 1
         2) 2
2) 1) "x=2"
   2) 1) 1) "x"
         2) "2"
      2) 1) "__reducer__"
         2) "sum"
      3) 1) "__source__"
         2) "t3"
   3) 1) 1) (integer) 1
         2) 1
```

Anyway, this is an interesting question. I'm not sure if we ever considered the case of using multiple values for the same label. It seems to work well, but you should be aware that when grouping by such a label - just one of the values is used for each time series.

**Comment by luasenvy** [comment]
thank you for reply.

i just they wanted it to calculate all labels:
```
TS.CREATE t1 labels x 1 x 3
TS.ADD t1 1 1
TS.CREATE t2 labels x 2 x 3
TS.ADD t2 1 2

TS.MRANGE - + WITHLABELS FILTER x=3 GROUPBY x REDUCE sum

1) 1) "x=1"
   2) 1) 1) "x"
         2) "1"
      2) 1) "__reducer__"
         2) "sum"
      3) 1) "__source__"
         2) "t1"
   3) 1) 1) "1"
         2) "1"
2) 1) "x=2"
   2) 1) 1) "x"
         2) "2"
      2) 1) "__reducer__"
         2) "sum"
      3) 1) "__source__"
         2) "t2"
   3) 1) 1) "1"
         2) "2"
```

include other same labels:
```
3) 1) "x=3"
   2) 1) 1) "x"
         2) "3"
      2) 1) "__reducer__"
         2) "sum"
      3) 1) "__source__"
         2) "t1,t2"
   3) 1) 1) "1"
         2) "1.5"
```

---

> you should be aware that when grouping by such a label - just one of the values is used for each time series.

thank you for notice me. now became clear.

if i need `x3` search `t1` and `t2`, reducing in application. :tada:

**Comment by LiorKogan** [comment]
Note that `GROUPBY` groups each series by the first value found.

This is what you'll get if you change the order of the values:

```
redis> TS.CREATE t1 LABELS x 3 x 1
redis> TS.ADD t1 1 1
redis> TS.CREATE t2 LABELS x 3 x 2
redis> TS.ADD t2 1 2

redis> TS.MRANGE - + WITHLABELS FILTER x=3 GROUPBY x REDUCE sum
1) 1) "x=3"
   2) 1) 1) "x"
         2) "3"
      2) 1) "__reducer__"
         2) "sum"
      3) 1) "__source__"
         2) "t1,t2"
   3) 1) 1) (integer) 1
         2) 3
```
