### ISSUE TITLE
can i give delay for CompactionRule?

### ISSUE THREAD

**Issue by luasenvy** [RedisTimeSeries/RedisTimeSeries#1573]
As an example,

If we assume that the maximum interval for late data reception is 3 days, taking into account data loss from the device.

Can I set CREATERULE to calculate based on data from 3 days ago?

I checked the alignTimestamp option, but It doesn't seem to change the calculation base date.

---

![image](https://github.com/RedisTimeSeries/RedisTimeSeries/assets/24634713/9deb4272-ca42-4f3c-a509-420605715ed0)

thank you.

**Comment by LiorKogan** [comment]
You can add data retrospectively. What matters is the timestamp of the sample, not when you add it.
Compactions buckets are updated accordingly.

I hope it answers your question,

**Comment by luasenvy** [comment]
> old data - compactions buckets are updated retrospectively

thank you for notice me. :tada:
