### ISSUE TITLE
TS.MRANGE filter labels!=. not work

### ISSUE THREAD

**Issue by csh720526** [RedisTimeSeries/RedisTimeSeries#1600]
i try to use ts.mrange filter filterExpr syntanx. labels!=1 , retrieve (error) ERR TSDB: please provide at least one matcher
did i use the wrong syntax?

![截圖 2024-05-09 19 14 36](https://github.com/RedisTimeSeries/RedisTimeSeries/assets/7006536/da693916-f392-4833-ad93-5252a68fe391)

**Comment by LiorKogan** [comment]
See `TS.MRANGE` documentation:

- At least one filter expression with a syntax label=value or label=(value1,value2,...) is required.
