### ISSUE TITLE
Log message is bring printed to stdout rather than logged

### ISSUE THREAD

**Issue by andresrinivasan** [RedisTimeSeries/RedisTimeSeries#184]
``` txt
loaded default MAX_SAMPLE_PER_CHUNK policy: 360
1:M 16 Aug 2019 22:39:29.605 * Module 'timeseries' loaded from /usr/lib/redis/modules/redistimeseries.so
```

The line `loaded default MAX_SAMPLE_PER_CHUNK policy: 360` appears to be coming from RedisTimeSeries.

**Comment by ashtul** [comment]
@andresrinivasan Indeed it does. It is in config.c file. It is by design.
@danni-m @gkorland should we change this?

**Comment by danni-m** [comment]
@ashtul Lets transform this to a log line instead of printf.
