### ISSUE TITLE
Document min and max placeholders for range commands

### ISSUE THREAD

**Issue by nosqlgeek** [RedisTimeSeries/RedisTimeSeries#213]
The documentation doesn't mention that a range command is accepting `-` (minimum) and `+` (maximum) for the arguments 'fromTimestamp' and 'toTimestamp'.

The following change is proposed for all commands that are accepting a time range as an argument

```
fromTimestamp - Start timestamp for range query, whereby the minimal possible value timestamp can be expressed as `-`
toTimestamp - End timestamp for range query, whereby the maximum possible timestamp can be expressed as `+`
```

**Comment by gkorland** [comment]
@nosqlgeek feel free to submit a PR
