### ISSUE TITLE
build of latest rev for macosx fails.

### ISSUE THREAD

**Issue by schaefer01** [RedisTimeSeries/RedisTimeSeries#218]
HI,
  I received an email yesterday (9/24) that the latest revision was out.
 I've got macosx 10.14.6
 at the step: make all, the following error was returned:
Linking ../bin/--release/redistimeseries.so...
Undefined symbols for architecture x86_64:
  "_intrev64", referenced from:
      _SeriesAddSample in tsdb.o
      _SeriesQuery in tsdb.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../bin/--release/redistimeseries.so] Error 1

**Comment by rafie** [comment]
From the repo root, please run the following commands and repeat the build:
./deps/readies/bin/getpy2
./system-setup.py

**Comment by schaefer01** [comment]
Rafi,

I attempted  ./system-setup.py but you could have warned me about “brew”, I vowed to never use brew again after my last attempt
to update brew update destroyed my working python environment. I am not a fan of virtual python environments.

I had to run your setup twice, the first failure was a python paths problem and I needed to copy my python2.7 to where it was expected to be.

The setup again failed, probably because I have a mix of python2 and python3 on my mac (note the construction: python/3.7.4/bin/python2.72.7 !!), we are transitioning our tools at work and I need both python2 and python3.

If you give up on helping me because of this, I understand.

the console output:

brew update || true
Already up-to-date.
pip install --disable-pip-version-check --user wheel
python2.7: posix_spawn: /usr/local/Cellar/python/3.7.4/bin/python2.72.7: No such file or directory
command failed: { pip install --disable-pip-version-check --user wheel; } >/var/folders/3t/kw0fs3s13jb7y204ylk18cc40000gn/T/tmpuy21A1 2>&1


bob s.

On Sep 25, 2019, at 2:00 PM, Rafi Einstein <notifications@github.com<mailto:notifications@github.com>> wrote:


From the repo root, please run the following commands and repeat the build:
./deps/readies/bin/getpy2
./system-setup.py

**Comment by rafie** [comment]
Hello Bob,
Sorry for the inconvenience in the setup process.
Setting up a stable build environment on arbitrary hosts is indeed a complicated task.
Thus, the system-setup.py file is provided both as a script and as documentation of the build system requirements.
Python 2.7 is a requirement as it is ubiquitous and provide enough automation power. We, however, do support Python 3.x as an alternative (but then one has to determine the x to get a consistent behavior, so problems do not end there).
There is no requirement for Python virtual environments in the build system.
From looking in the output of your build commands, I can estimate that a working Python 2.7 installation will satisfy the build system.
