### ISSUE TITLE
Retrieve the number of samples in a timeseries

### ISSUE THREAD

**Issue by K-Jo** [RedisTimeSeries/RedisTimeSeries#220]
TS.RANGE, MRANGE
```
TS.RANGE ts - + AGGREGATION count -1
```
would allow you to count the number of samples in a series although O(n)

**Comment by ashtul** [comment]
This is a great functionality but this isn't the right way to provide it.
A user can provide MAXUNSIGNEDLONGLONG to get the same way.
User are likely to send a negative number erroneously and we should notify them of it.

**Comment by K-Jo** [comment]
Doesn't need to be the above command, hence the rename of the issue

**Comment by ashtul** [comment]
Should be part of ts.info as you suggested

**Comment by K-Jo** [comment]
```
TS.INFO EXTRA
```
as discussed with @ashtul 
sorry for confusion on initial comment

**Comment by K-Jo** [comment]
moved to #234
