### ISSUE TITLE
Is there an option to fill irregular time series.

### ISSUE THREAD

**Issue by peet83** [RedisTimeSeries/RedisTimeSeries#223]
Hi,

My data stream comes in irregular time frames.  Like

1570525959 20
1570525960 21
1570525965 22
1570525968 23

Is there any way to fill the missing seconds in the above dataset, What Im expecting is

1570525959 20
1570525960 21
1570525961 21
1570525962 21
1570525963 21
1570525964 21
1570525965 22
1570525966 22
1570525967 22
1570525968 23
1570525969 23

Thank you,

**Comment by ashtul** [comment]
@peet83 this sort of data manipulation should be done on the client side.

**Comment by ashtul** [comment]
@peet83 
I hope my reply answered your question.
Many analytics systems will do it for you by either smoothing the existing results or treating them as columns. 
You will be wasting memory space on data that you can produce on the fly.

**Comment by peet83** [comment]
ok , got it thank you

**Comment by ashtul** [comment]
@peet83 
Thank you for the feedback. We will consider adding a flag on TS.RANGE that will take care of this. As for now, unfortunately, it isn't supported.
