### ISSUE TITLE
Is there any limit of maximum data points in a single key 

### ISSUE THREAD

**Issue by peet83** [RedisTimeSeries/RedisTimeSeries#225]
Hi,

Is there any data point limitation in timeseries key. Im planning to keep 7 days of seconds data points in a single key, ie  604800 data points and values in a single key.

Please let me know if that is the efficient way to store data in time series and any performance issues.

Thank you,
Peter

**Comment by gkorland** [comment]
There shouldn't be any issue with that.
The time is represented by a 64bit and is planned to hold milliseconds
