### ISSUE TITLE
Redis server is crashing upon loading RedisTimeSeries module in ARM 32 v7

### ISSUE THREAD

**Issue by VeerPV** [RedisTimeSeries/RedisTimeSeries#226]
Hi,
I'm trying to cross compile RedisTimeSeries to ARM. It's getting failed. But on the host machine (Ubuntu 16 having gcc version 5.40) successfully compiles.

My cross GCC version is 5.3.0. Is it causing issue?. What should be the compiler version to compile this library?.

my target is arm32 v7

Here is the log:

GNU C99 (GCC) version 5.3.0 (arm-phytec-linux-gnueabi)
	compiled by GNU C version 5.3.0, GMP version 6.1.0, MPFR version 3.1.3, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/not/exist/usr/lib/gcc/arm-phytec-linux-gnueabi/5.3.0/include"
ignoring nonexistent directory "/not/exist/usr/local/include"
ignoring nonexistent directory "/opt/ir_uc_sdk/sysroots/x86_64-yogurtsdk-linux/usr/lib/arm-phytec-linux-gnueabi/gcc/arm-phytec-linux-gnueabi/5.3.0/../../../../../arm-phytec-linux-gnueabi/include"
ignoring nonexistent directory "/not/exist/usr/include"

**Comment by rafie** [comment]
Could you please try to reproduce this with a Docker image? Thanks.

**Comment by VeerPV** [comment]
Hi rafie,
I'm doing native compilation now. It's compiled. But when I load the module. redis-server is crashing with segmentation fault. Here is the log:


=== REDIS BUG REPORT START: Cut & paste starting from here ===
515:M 17 Oct 14:04:47.371 # Redis 4.0.8 crashed by signal: 11
515:M 17 Oct 14:04:47.374 # Accessing address: (nil)
515:M 17 Oct 14:04:47.376 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------

------ INFO OUTPUT ------
# Server
redis_version:4.0.8
redis_git_sha1:0f5cf961
redis_git_dirty:1
redis_build_id:21d1af0ed9bdb5c4
redis_mode:standalone
os:Linux 4.14.134 armv7l
arch_bits:32
multiplexing_api:epoll
atomicvar_api:pthread-mutex
gcc_version:8.2.0
process_id:515
run_id:b05c7c8c9159818185ea50d9616f3b0114f920b2
tcp_port:6379
uptime_in_seconds:82
uptime_in_days:0
hz:10
lru_clock:11039999
executable:/home/root/redis-server
config_file:

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:670065
used_memory_human:654.36K
used_memory_rss:2138112
used_memory_rss_human:2.04M
used_memory_peak:670065
used_memory_peak_human:654.36K
used_memory_peak_perc:100.18%
used_memory_overhead:668658
used_memory_startup:619132
used_memory_dataset:1407
used_memory_dataset_perc:2.76%
total_system_memory:1043972096
total_system_memory_human:995.61M
used_memory_lua:27648
used_memory_lua_human:27.00K
maxmemory:3221225472
maxmemory_human:3.00G
maxmemory_policy:noeviction
mem_fragmentation_ratio:3.19
mem_allocator:libc
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1571321005
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:1
instantaneous_ops_per_sec:0
total_net_input_bytes:118
total_net_output_bytes:7
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:dbb4754ec48902c5f9fa54d576c8e4e23b47cada
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.30
used_cpu_user:0.09
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_ping:calls=1,usec=4,usec_per_call=4.00

# Cluster
cluster_enabled:0

# Keyspace

------ CLIENT LIST OUTPUT ------
id=2 addr=127.0.0.1:54066 fd=8 name= age=17 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=module

------ CURRENT CLIENT INFO ------
id=2 addr=127.0.0.1:54066 fd=8 name= age=17 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=module
argv[0]: 'MODULE'
argv[1]: 'LOAD'
argv[2]: '/home/root/RedisTimeSeries/bin/linux-arm32v7-release/redistimeseries.so'

------ REGISTERS ------

------ FAST MEMORY TEST ------
515:M 17 Oct 14:04:47.399 # Bio thread for job type #0 terminated
515:M 17 Oct 14:04:47.399 # Bio thread for job type #1 terminated
515:M 17 Oct 14:04:47.400 # Bio thread for job type #2 terminated
*** Preparing to test memory region 50a000 (49152 bytes)
*** Preparing to test memory region 18e6000 (548864 bytes)
*** Preparing to test memory region b5518000 (8388608 bytes)
*** Preparing to test memory region b5d19000 (8388608 bytes)
*** Preparing to test memory region b651a000 (8716288 bytes)
*** Preparing to test memory region b6e5a000 (12288 bytes)
*** Preparing to test memory region b6e80000 (8192 bytes)
*** Preparing to test memory region b6f33000 (8192 bytes)
.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/antirez/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

Segmentation fault

**Comment by VeerPV** [comment]
Do I need to change some options in existing make file when I'm doing native compilation on the ARM board?.
I also tried modifying make file 

Also redis-server version is 4.0.8, is it fine for RedisTimeSeries?

**Comment by VeerPV** [comment]
I was Trying on redis 4.08. Hence the crash. On redis-stable 5.05. This module is getting loaded and working as expected.
It will be helpful if you mention supporting verisions of redis server for this module to be loaded.
