### ISSUE TITLE
Documentation terms

### ISSUE THREAD

**Issue by hello-error** [RedisTimeSeries/RedisTimeSeries#227]
Hello, in documentation about default compaction policies https://oss.redislabs.com/redistimeseries/configuration/
The language/explanation is very confusing and misleading.
'''
Each rule is separated by a semicolon (;), the rule consists of several fields that are separated by a colon (:): aggregation function - avg, sum, min, max, count, first, last time bucket - number and the time representation (Example for 1 minute: 1M) * m - millisecond * M - minute * s - seconds * d - day * retention time - in milliseconds

Example:

max:1m:1h - Aggregate using max over 1 minute and retain the last 1 hour
'''
It says m - millisecond, then in example 1m is 1 minute ?

In https://oss.redislabs.com/redistimeseries/commands/#create-example, for rule creation

"timeBucket - Time bucket for aggregation in milliseconds"

However, it is in seconds from our experience setting it.

**Comment by ashtul** [comment]
@hello-error thanks for your feedback. You are correct! #228

**Comment by hello-error** [comment]
Slight change: if the timestamp supplied in metrics is in unix milliseonds resolution, default compactions are correct. If the unix timestamp is in seconds, that is when default compaction rules are not as expected. In the latter scenario, creating a rule manually requires seconds level aggregation again. Bottom line, I understand, timestamps for metrics must be in milliseconds level unix time. Thanks
