### ISSUE TITLE
There is any  Keyspace Notifications for RedisTimeSeries

### ISSUE THREAD

**Issue by llerrito** [RedisTimeSeries/RedisTimeSeries#231]

**Comment by gkorland** [comment]
Pending https://github.com/antirez/redis/pull/6481

**Comment by federico-ercoles** [comment]
@gkorland Hi, I saw that the PR you mentioned was merged a few months ago and is going to be in the next release of Redis, has any work been done to implement keyspace notifications for time series?

**Comment by gkorland** [comment]
@federico-ercoles no work has been done yet, but it's on the roadmap

**Comment by danni-m** [comment]
@federico-ercoles this was implemented on master and will be released in the upcoming 1.6 version.
