### ISSUE TITLE
Support for aggregations over multiple keys

### ISSUE THREAD

**Issue by peet83** [RedisTimeSeries/RedisTimeSeries#235]
Hai again,

Is there any way to do aggregation on data points which is spreaded over multiple keys. Taking from the example, 127.0.0.1:6379> TS.MRANGE 1548149180000 1548149210000 AGGREGATION avg 5000 FILTER area_id=32 sensor_id!=1
1) 1) "temperature:2:32"
   2) 1) 1) "sensor_id"
         2) "2"
      2) 1) "area_id"
         2) "32"
   3) 1) 1) (integer) 1548149180000
         2) "27.600000000000001"
      2) 1) (integer) 1548149185000
         2) "23.800000000000001"
      3) 1) (integer) 1548149190000
         2) "24.399999999999999"
      4) 1) (integer) 1548149195000
         2) "24"
      5) 1) (integer) 1548149200000
         2) "25.600000000000001"
      6) 1) (integer) 1548149205000
         2) "25.800000000000001"
      7) 1) (integer) 1548149210000
         2) "21"
2) 1) "temperature:3:32"
   2) 1) 1) "sensor_id"
         2) "3"
      2) 1) "area_id"
         2) "32"
   3) 1) 1) (integer) 1548149180000
         2) "26.199999999999999"
      2) 1) (integer) 1548149185000
         2) "27.399999999999999"
      3) 1) (integer) 1548149190000
         2) "24.800000000000001"
      4) 1) (integer) 1548149195000
         2) "23.199999999999999"
      5) 1) (integer) 1548149200000
         2) "25.199999999999999"
      6) 1) (integer) 1548149205000
         2) "28"
      7) 1) (integer) 1548149210000
         2) "20"

The expected result is AVG of both keys temperature:2:32 and temperature:3:32 with FILTER area_id=32 sensor_id!=1. Is there any alternatives to achieve the same as FILTERS will be meaning less if we can group them multiple keys.

Thanks

**Comment by peet83** [comment]
Thank you for looking into this and your efforts are really appreciated.

Peter

**Comment by danni-m** [comment]
@peet83 FYI we implemented `GROUPBY` feature on master, it will be released in the upcoming 1.6 version
