### ISSUE TITLE
Compilation Error in  CentOS7

### ISSUE THREAD

**Issue by WXY3** [RedisTimeSeries/RedisTimeSeries#240]
![image](https://user-images.githubusercontent.com/34730095/68738797-30774900-0622-11ea-82f1-2d9fd2325ba9.png)

**Comment by rafie** [comment]
It seems like files under deps/readies/bin lack execution permission.
Can you please describe your work environment (e.g., any network file system?) and how do you actually get RedisTimeSeries repo into your system.
If you have no luck of setting up your machine properly, you can build using Docker and copying the results back into your machine.

**Comment by WXY3** [comment]
@rafie I compiled it with the following method
https://oss.redislabs.com/redistimeseries/

![image](https://user-images.githubusercontent.com/34730095/68745605-edbd6d00-0631-11ea-8c53-092e963fa9d0.png)

**Comment by WXY3** [comment]
> It seems like files under deps/readies/bin lack execution permission.
> Can you please describe your work environment (e.g., any network file system?) and how do you actually get RedisTimeSeries repo into your system.
> If you have no luck of setting up your machine properly, you can build using Docker and copying the results back into your machine.

@rafie Can you trying on CentOS7 ，I want to use RedisTimeSeries in production environment.

**Comment by rafie** [comment]
Please use build instructions from https://github.com/RedisTimeSeries/RedisTimeSeries. We will update the docs.

**Comment by WXY3** [comment]
> Please use build instructions from https://github.com/RedisTimeSeries/RedisTimeSeries. We will update the docs.

@rafie Can you trying on CentOS7 ,I tried a lot of methods but didn't succeed at one time，including your method（use build instructions from https://github.com/RedisTimeSeries/RedisTimeSeries）.

**Comment by rafie** [comment]
I have no problem building on CentOS 7, both native and Docker.
Can you please send the session output after applying the build instructions?
