### ISSUE TITLE
RETENTION field overflow int32

### ISSUE THREAD

**Issue by ng5** [RedisTimeSeries/RedisTimeSeries#252]
Docker Image Version:
redislabs/redismod           latest              c9ffc8f9b58a        7 days ago          444MB

Issue:

We have daily samples for 5 years. we wanted to keep only 5 years data therefore i tried to add retention period of 5 years (in milliseconds), but looks like it is causing 32 bit integer to overflow.

Can this field be set to int64_t please. Thanks

`
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379> TS.CREATE SAMPLE.5Y RETENTION 157784760000
OK
127.0.0.1:6379> TS.INFO SAMPLE.5Y
 1) lastTimestamp
 2) (integer) 0
 3) retentionTime
 4) (integer) **-1129029952**
 5) chunkCount
 6) (integer) 1
 7) maxSamplesPerChunk
 8) (integer) 360
 9) labels
10) (empty list or set)
11) sourceKey
12) (nil)
13) rules
14) (empty list or set)
127.0.0.1:6379> 

`

**Comment by gkorland** [comment]
@ng5 thanks for reporting it seems like it should have been unsigned 64bit

**Comment by ashtul** [comment]
@ng5 Can you please try to reproduce this bug?
This was fixed in PRs #199 #200

**Comment by ashtul** [comment]
I have just confirm using `docker run -p 6379:6379 -it --rm redislabs/redistimeseries:edge`
```127.0.0.1:6379> TS.CREATE SAMPLE.5Y RETENTION 157784760000
OK
127.0.0.1:6379> TS.INFO SAMPLE.5Y
 1) totalSamples
 2) (integer) 0
 3) memoryUsage
 4) (integer) 4136
 5) firstTimestamp
 6) (integer) 0
 7) lastTimestamp
 8) (integer) 0
 9) retentionTime
10) (integer) 157784760000
11) chunkCount
12) (integer) 1
13) maxSamplesPerChunk
14) (integer) 256
15) labels
16) (empty list or set)
17) sourceKey
18) (nil)
19) rules
20) (empty list or set)
```

**Comment by ng5** [comment]
I was using latest version of below image, which bundle full text search module. Thanks for checking out, I confirm fix  is now also available on below image:

***redislabs/redismod***

**Comment by ashtul** [comment]
@ng5
Thank you for confirming this.
Can we close the issue then?

**Comment by ng5** [comment]
Done. Thank you.
