### ISSUE TITLE
TS.MADD - Redis maxmemory (noeviction) not recognized

### ISSUE THREAD

**Issue by ng5** [RedisTimeSeries/RedisTimeSeries#253]
TS.ADD command keeps on adding data regardless of maxmemory (& noeviction policy). 
This is not a major issue for us, raising it here so that it can be useful for someone else. I understand module use low level redis API therefore able to bypass Redis settings.  Not sure if these sort of things are supposed to be handled by Redis Module API.

I was expecting module will honour basic Redis settings with:

**OOM command not allowed when used memory > ‘maxmemory’**

**Comment by gkorland** [comment]
@ng5 thanks for reporting, it's very strange, we'll have to check it. Indeed modules are using low level API can override the memory policy, but we make sure to keep and TS.ADD is also keeping it see: https://github.com/RedisTimeSeries/RedisTimeSeries/blob/96cc3386633019646219b852a2945ca3406f0f05/src/module.c#L1049.

**Comment by gkorland** [comment]
@ng5 which version are you using?

**Comment by ng5** [comment]
Docker Image Version:
redislabs/redismod latest c9ffc8f9b58a 7 days ago 444MB

Please check TS.MADD command instead of TS.ADD. i've updated the title.

**Comment by gkorland** [comment]
It also seems OK https://github.com/RedisTimeSeries/RedisTimeSeries/blob/96cc3386633019646219b852a2945ca3406f0f05/src/module.c#L1057

But we'll double check it ...

**Comment by ng5** [comment]
My apologies, I can no longer reproduce this bug therefore closing it now. I'm pretty sure i saw memory going past maxmemory but not able to narrow down exact scenario that lead to it.

**Comment by ashtul** [comment]
@ng5 It was fixed in PR #211
