### ISSUE TITLE
TS.RANGE returns inaccurate values

### ISSUE THREAD

**Issue by streamtv85** [RedisTimeSeries/RedisTimeSeries#262]
Hi,
I spotted some inconsistencies when writing and reading float values to/from redistimeseries database with python.
Here is an example of code showing the problem:

```
>>> from redistimeseries.client import Client
>>> redis_host = '192.168.99.100'; redis_pw = "foobar"; key = 'test'
>>> rts = Client(host=redis_host, port=6379, db=0, password=redis_pw)
>>> rts.flushall()
True
>>> rts.create(key, labels={'Time': 'Series'})
True
>>> for i in range(1, 10):
...     rts.add(key, i, 1.12 * i)
...     

>>> print(rts.get(key))
(9, 10.080000000000002)

>>> print(rts.range(key, 0, -1))  # get all
[(1, '1.1200000000000001'), (2, '2.2400000000000002'), (3, '3.3600000000000003'), (4, '4.4800000000000004'), (5, '5.6000000000000005'), (6, '6.7200000000000006'), (7, '7.8400000000000007'), (8, '8.9600000000000009'), (9, '10.080000000000002')]

```

So, I see two problems here:
1. TS.RANGE returns inaccurate numbers (looks like a rounding error)
2. TS.RANGE returns string values (thus requiring additional conversion) while TS.GET returns float value

Versions:

python libraries:
redis==3.3.11
redistimeseries==0.4
server is just a docker image redislabs/redistimeseries:1.0.3

**Comment by gkorland** [comment]
It seems like an issue on the python client

**Comment by ashtul** [comment]
@gkorland same behavior on redis-cli
```
127.0.0.1:6379> TS.CREATE a
OK
127.0.0.1:6379> TS.ADD a * 1.12
(integer) 1575628036880
127.0.0.1:6379> ts.get a
1) (integer) 1575628036880
2) "1.1200000000000001"
127.0.0.1:6379> 
```

**Comment by ashtul** [comment]
@gkorland 
The above fix didn't change the behavior. We still return a float with inaccuracies. I don't see a possible fix. 
Should we close?

**Comment by ashtul** [comment]
@streamtv85
Floats behave this way and it is to be expected.
You have two options -
1. if you know your precision point, make it into an integer by multiplication before sending and divide once you get the number back. Ex. 1.2 -> 12 -> 1.2. 3.98 -> 398 -> 3.98.
2. use a system function to round the number. In Python use round(value, precision). In C you can read [here](https://stackoverflow.com/questions/1343890/rounding-number-to-2-decimal-places-in-c).
