### ISSUE TITLE
RETENTION does not actually remove old data point

### ISSUE THREAD

**Issue by wiwat-tharateeraparb** [RedisTimeSeries/RedisTimeSeries#263]
Current time-series
```
127.0.0.1:6379> ts.range test - +
1) 1) (integer) 1575606169504
   2) "1"
2) 1) (integer) 1575606240600
   2) "1"
3) 1) (integer) 1575606243426
   2) "2"
4) 1) (integer) 1575606245854
   2) "3"
5) 1) (integer) 1575606250346
   2) "34"
6) 1) (integer) 1575607228211
   2) "35"
7) 1) (integer) 1575607651240
   2) "36"
8) 1) (integer) 1575607698324
   2) "37"
9) 1) (integer) 1575607701377
   2) "38"
```
Alter `RETENTION` to 10,000 ms.
```
127.0.0.1:6379> ts.alter test retention 10000
OK
```
Query again seems OK. Older time-series are not included in the result.
```
127.0.0.1:6379> ts.range test - +
1) 1) (integer) 1575607698324
   2) "37"
2) 1) (integer) 1575607701377
   2) "38"
```
Then, change `RETENTION` to 0
```
127.0.0.1:6379> ts.alter test retention 0
OK
```
Query again
```
127.0.0.1:6379> ts.range test - +
1) 1) (integer) 1575606169504
   2) "1"
2) 1) (integer) 1575606240600
   2) "1"
3) 1) (integer) 1575606243426
   2) "2"
4) 1) (integer) 1575606245854
   2) "3"
5) 1) (integer) 1575606250346
   2) "34"
6) 1) (integer) 1575607228211
   2) "35"
7) 1) (integer) 1575607651240
   2) "36"
8) 1) (integer) 1575607698324
   2) "37"
9) 1) (integer) 1575607701377
   2) "38"
```

Is there anyway to actually remove/truncate older data point forever?

**Comment by ashtul** [comment]
@wiwat-tharateeraparb 
Thank you for opening the issue. 
This behavior you describe is expected.
Samples are not being retired individually after their retention has passed, rather they are being filtered by the query function. Only when an entire chunk of memory has retired, the whole chunk is being disposed of.
The default size for a chunk is 256 samples and therefore, only after the last sample has retired, the whole chunk, and with it, the 256 samples, will be deleted.
If you would like faster 'retirement', you can use a smaller chunk size.

**Comment by wiwat-tharateeraparb** [comment]
How can I configure for chunk size? Is it possible to configure for individual key?

**Comment by ashtul** [comment]
@wiwat-tharateeraparb TS.CREATE has [CHUNK_SIZE integer] option which can be used to change the default of 256 samples per chunk.
Please note, this feature isn't official and its behavior may change when we start storing compressed data. You would likely still be able to use the flag with an uncompressed chunk.
