### ISSUE TITLE
Support for TS.DEL to remove specific entries from series

### ISSUE THREAD

**Issue by wiwat-tharateeraparb** [RedisTimeSeries/RedisTimeSeries#264]
Similar to https://redis.io/commands/xdel

**Comment by gkorland** [comment]
@wiwat-tharateeraparb thanks for your feedback, can you please describe the scenario that requires this feature?

**Comment by wiwat-tharateeraparb** [comment]
We need `TS.DEL` in order to:
* Comply with some user privacy policies
* Remove erroneous data points
* Be able to remove old data points without relying on `RETENTION`

**Comment by nightwolfz** [comment]
We too have exactly the same use-case, it's the only thing stopping us from adopting RedisTimeSeries

**Comment by ashtul** [comment]
@nightwolfz 
We plan on adding this in the near future
