### ISSUE TITLE
RANGE with value filtering 

### ISSUE THREAD

**Issue by filipecosta90** [RedisTimeSeries/RedisTimeSeries#275]
Returns all the elements in the series with a value between min and max. Exclusive intervals and infinity.
min and max can be -inf and +inf ( or a symbol that represents it ), so that you are not required to know the highest or lowest value in the time series to get all elements from or up to a certain limit.

By default, the interval specified by min and max is closed (inclusive). It is possible to specify an open interval (exclusive) by prefixing the score with the character (. 

Using the same api and specifications as https://redis.io/commands/zrangebyscore

**Comment by SutnuiBorshik** [comment]
Will this feature be available for MRANGE command as well?
And is there a rough estimate on version 1.4 release?

**Comment by gkorland** [comment]
> Will this feature be available for MRANGE command as well?
@SutnuiBorshik probably

>  And is there a rough estimate on version 1.4 release?
Should be in the next couple of months, we still don't have final release date

**Comment by SutnuiBorshik** [comment]
Thanks @gkorland. I'll be anxiously waiting.
Keep up a good work!

**Comment by danni-m** [comment]
Merged to master.
