### ISSUE TITLE
Add does not update the key and value for a same timestamp

### ISSUE THREAD

**Issue by harishkumarr95** [RedisTimeSeries/RedisTimeSeries#295]
For my requirement, I was using Redistimeseries module and I have been getting this error saying that

`TSDB: Timestamp cannot be older than the latest timestamp in the time series`

I want to update the Values in the key for the same timestamp by using the command

`TS.ADD`

I hope this is an issue as the value should be updated for the same timestamp and not throw an error.

**Comment by ashtul** [comment]
At the moment, this is the desired and expected behavior.

**Comment by nightwolfz** [comment]
This would be an incredibly useful feature to have. Any plans on implementing this?

**Comment by danni-m** [comment]
@nightwolfz we just pushed "out of order" implementation to master, please take it for a spin. There's a big caveat on this feature that it is not time optimized, meaning that when you insert not in order you will occur a time penalty.
