### ISSUE TITLE
Is WITHLABELS flag not working in last release 1.2.1?

### ISSUE THREAD

**Issue by averias** [RedisTimeSeries/RedisTimeSeries#329]
As per documentation: 
`WITHLABELS - Include in the reply the label-value pairs that represent metadata labels of the time-series. If this argument is not set, by default, an empty Array will be replied on the labels array position.`

But TS.MRANGE and TS.MGET returns a labels array, not empty, when WITHLABELS flag is not provided (default behavior).

Example:
127.0.0.1:6379[14]> TS.ADD temperature:2:32 1548149180000 26 LABELS sensor_id 2 area_id 32
(integer) 1548149180000
127.0.0.1:6379[14]> TS.ADD temperature:2:32 1548149190000 27
(integer) 1548149190000
127.0.0.1:6379[14]> TS.ADD temperature:2:32 1548149200000 28
(integer) 1548149200000
127.0.0.1:6379[14]> TS.ADD temperature:2:32 1548149210000 29
(integer) 1548149210000

127.0.0.1:6379[14]> **TS.MRANGE 1548149180000 1548149210000 AGGREGATION avg 5000 FILTER area_id=32 sensor_id!=1**
```
1) 1) "temperature:2:32"
   2) 1) 1) "sensor_id"
         2) "2"
      2) 1) "area_id"
         2) "32"
   3) 1) 1) (integer) 1548149180000
         2) "26"
      2) 1) (integer) 1548149190000
         2) "27"
      3) 1) (integer) 1548149200000
         2) "28"
      4) 1) (integer) 1548149210000
         2) "29"
```

127.0.0.1:6379[14]> **TS.MRANGE 1548149180000 1548149210000 AGGREGATION avg 5000 WITHLABELS FILTER area_id=32 sensor_id!=1**
```
1) 1) "temperature:2:32"
   2) 1) 1) "sensor_id"
         2) "2"
      2) 1) "area_id"
         2) "32"
   3) 1) 1) (integer) 1548149180000
         2) "26"
      2) 1) (integer) 1548149190000
         2) "27"
      3) 1) (integer) 1548149200000
         2) "28"
      4) 1) (integer) 1548149210000
         2) "29"
```

127.0.0.1:6379[14]> **TS.MGET FILTER area_id=32**
```
1) 1) "temperature:2:32"
   2) 1) 1) "sensor_id"
         2) "2"
      2) 1) "area_id"
         2) "32"
   3) (integer) 1548149210000
   4) "29"
```

127.0.0.1:6379[14]> **TS.MGET WITHLABELS FILTER area_id=32**
```
1) 1) "temperature:2:32"
   2) 1) 1) "sensor_id"
         2) "2"
      2) 1) "area_id"
         2) "32"
   3) (integer) 1548149210000
   4) "29"
```

**Comment by ashtul** [comment]
@averias 
It looks like you are not running the latest version. The return array for meet had changed a bit as well.

**Comment by averias** [comment]
you're right @ashtul, sorry my bad, I thought that latest docker image matched version 1.2.1
