### ISSUE TITLE
[RFC/Feature] Add support for TS.RANGE + COUNT + Aggregation 

### ISSUE THREAD

**Issue by lyrixx** [RedisTimeSeries/RedisTimeSeries#331]
Hello.

I udpated my redis to use the 1.2.2

I tried something and I can not make it work.

I would be nice to be able to write te following command:

```
TS.RANGE test 0 1580320148753 COUNT 4 AGGREGATION avg
```

You can notice I omit the timeBucket parameter.

To say it differently:

> Over a period I want 4 data points that represent the local average 

And of course, I don't want the first 4 points, I want only 4 points on the whole interval

**Comment by ashtul** [comment]
Hello @lyrixx ,
This is the expected behavior. 
You could get your results but passing a `timeBucket` argument of `(1580320148753 - 0) / 4`.
You can even get the first/last sample from TS.INFO and use them with the above calculation.

**Comment by lyrixx** [comment]
Thanks for your fast reply.

I noticed the fist / last sampled is now exposed. This is very cool. This is what I will do if you decide to not implement this idea. 

Thanks anyway 👍
