### ISSUE TITLE
[Bug] Adding data to a timeseries fails on high concurrency 

### ISSUE THREAD

**Issue by lyrixx** [RedisTimeSeries/RedisTimeSeries#333]
Hello

I get often the following error:
```
(error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
```

I use the following command:
```
TS.ADD test * 1
```

It occurs when call frequency is too high
I'm using a golang worker, and I use goroutine (concurrency).

I managed to create a very simple reproducer:

```bash
#!/usr/bin/env bash

for i in `seq 1 100`; do
    redis-cli -h redis TS.ADD test '*' 1 &
done
```

You should notice the trailing `&` to run many redis command at the "same time", or at least as close as possible.

---

I don't really understand why I hit this issue, and how I can avoid it since I used `*` for the timestamp

**Comment by gkorland** [comment]
RedisTimeSeries time resolution is in milliseconds, while on the other hand timestamp must be unique. Therefor one event per millisecond is allowed for each timeseries, which means that in case you use `*` two parallel events might get the same timestamp and the second will be rejected.

**Comment by lyrixx** [comment]
In my application, I added a retry mechanism. This is not perfect, but it does the job.

Who could we fix this issue?

**Comment by ashtul** [comment]
Hi @lyrixx,
You write that you have a retry mechanism. So if I understand correctly it means the time stamp isn't as crucial, and if a sample will be assigned the following timestamp it will be sufficient for your use case?

For example - if two samples arrive together, the first assigned `timestamp` and inserted, then the next one happened to receive the same `timestamp`. The current behavior is to reject the second sample. But if it would be accepted with `timestamp+1`, will that work for you?
Please note that for a high load the delta to the real timestamp value could be significant.

At the moment we do not plan to allow multiple values in one timestamp but if this will work for your use-case, we can consider it.

**Comment by lyrixx** [comment]
> You write that you have a retry mechanism. So if I understand correctly it means the time stamp isn't as crucial, and if a sample will be assigned the following timestamp it will be sufficient for your use case?

Sure, this is not an issue at all (for my usecase)

> Please note that for a high load the delta to the real timestamp value could be significant.

Yes, I'm a bit afraid of that. 
but for now, I'm writing about 200 data point per second (1 data point per AMQP message). 
So it means I'm using 200 points over 1 000 000 (numbrer of ms in one second)

**Comment by danni-m** [comment]
@lyrixx can you please elaborate further how you insert and query your data and whats the meaning of the values?

**Comment by lyrixx** [comment]
Sure :) 

I'm building an HTTP crawler. Each time I discover / download / analyse / save a page, I added a data point in corresponding TS.
So If the website is quite fast, some race condition appear

Then I read theses TS data and I display them in near real time in the browser 

![crawler](https://user-images.githubusercontent.com/408368/76404634-1149b780-6387-11ea-857f-d707303f7a27.gif)

**Comment by eadz** [comment]
I am happy with the timestamp+1 approach too. I think if you are putting "*" for your timestamp it is not super critical.

**Comment by lyrixx** [comment]
@eadz I already have `*` for my timestamps. Few days ago, I retried for 10 times and then I give up. And I got an error in production. Now I put the limit to 20 :grimacing: I don't really like this kind of "hack"

**Comment by danni-m** [comment]
@lyrixx we're working on Out of order inserts and updates to existing data samples.
We want to better understand your usecase.  
if I understand correctly, you are pushing a monotonically increasing counters every 1 MS or more. So if you report on the same timestamp you would be OK with having the latest sample, right?
Whats your expectation of the module when you hit the same timestamp thats already there?

**Comment by danni-m** [comment]
Also would you say if https://oss.redislabs.com/redistimeseries/commands/#tsincrbytsdecrby would be a better fit for your use-case?

**Comment by eadz** [comment]
What I mean is, for my use case, I will be happy if redistimeseries automatically increments it. 

Looking at the code:

https://github.com/RedisTimeSeries/RedisTimeSeries/blob/61fb8252e42420060ce9840183fd9049ac89d3f2/src/tsdb.c#L220

```c
if (timestamp <= series->lastTimestamp && series->lastTimestamp != 0) {
        return TSDB_ERR_TIMESTAMP_TOO_OLD;
```
maybe the following change would work? ( of course, if there are many requests things will go into the future until there is a catchup period )
```c
if (timestamp <= series->lastTimestamp && series->lastTimestamp != 0) {
        timestamp = series->lastTimestamp + 1;
```

( I'm not a c programmer, maybe that is not the right syntax )

Another thing you could do, is scale the timeseries. 

So the timestamp dates from 1970 and goes up to year 2032(?)

But maybe for your purposes you only need 1 month of history. 

So you could instead scale the timestamp, where you do a calculation so that a timestamp represents time between 2020-2021 and you get a bit more precision

**Comment by eadz** [comment]
Just to clarify my use case

 - A time series of website requests. A website request could happen in the same millisecond, that is the issue. But if the data is out by a few milliseconds, that isn't the end of the world.

**Comment by ashtul** [comment]
@eadz 
We can consider your suggestion as a flag for TS.ADD command.
Thank you for all the input.

**Comment by lyrixx** [comment]
> Also would you say if https://oss.redislabs.com/redistimeseries/commands/#tsincrbytsdecrby would be a better fit for your use-case?

Oh, I missed that in my use case. Indeed I must use this command. (and :facepalm: because I use this command at some other places haha). I will try it ASAP (next week)

**Comment by lyrixx** [comment]
Actually, I already use TS.INCRBY to store and display the graph I put in a [previous comment](https://github.com/RedisTimeSeries/RedisTimeSeries/issues/333#issuecomment-597542014) and it looks like everything is fine with this.

But I also use TS.ADD to store the number of error over the time. When there are too many error I do some stuff. So in this case I can not use TS.INCRBY because I need the real number of error on a period. IIRC, I have tried to use TS.INCRBY and some magic to get the number of event (count in "end" MINUS  count in "start") but it was too complicated and it did not worked well.

So I really need TS.ADD to work with high concurrency

**Comment by danni-m** [comment]
@lyrixx 
If I understand correctly have a counter (that can only increase over time) that you keep in your app for error and you pushing that counter from different threads.

1. How do you handle the synchronisation between the threads? if each thread has his own counter, pushing to 1 key will not make a lot of sense.
2. "I need the real number of error on a period" - Would you say that an aggregation that will calculate the difference between the start and end of a period will suffice?

Also, we just pushed "out of order" implementation to master, please take it for a spin. There's a big caveat on this feature that it is not time optimized, meaning that when you insert not in order you will occur a time penalty.

**Comment by lyrixx** [comment]
Oh, BTW in my log I found that the faulty line was : 
```php
    $this->redis()->tsIncrement("crawler:$crawlId:ts:g:analyzed", 1);
```
So the error comes from also `TS.INCRBY`

**Comment by danni-m** [comment]
> Oh, BTW in my log I found that the faulty line was :
> 
> ```
>     $this->redis()->tsIncrement("crawler:$crawlId:ts:g:analyzed", 1);
> ```
> 
> So the error comes from also `TS.INCRBY`

Can you check if `tsIncrement` uses `*` or a specific timestamp?

**Comment by lyrixx** [comment]
The command is `TS.INCRBY <key> <value>` So it does not use a timestamp at all. So I guess it's the same as `*`

**Comment by danni-m** [comment]
@lyrixx now that we have DUPLICATE_POLICY and out-of-order inserts, do you think we are missing something to allow you to use RTS?

**Comment by lyrixx** [comment]
I didn't know about DUPLICATE_POLICY, that's very nice 👍🏼 (Here is a [link to the documentation](https://oss.redislabs.com/redistimeseries/configuration/#duplicate_policy), for other readers)

I'm closing this issue, it's all good for me

Thanks a lot for this project, and your time to fix my issue 💛
