### ISSUE TITLE
TS.MRANGE changes response in each release

### ISSUE THREAD

**Issue by averias** [RedisTimeSeries/RedisTimeSeries#341]
I have a use case in my tests which basically make an MRANGE on a key which has no data for the timestamp range specified, so basically I first created and add data with a timestamp in the last year 2019 on that time-series key and then I made a TS.RANGE with a timestamp range y the last 10 milliseconds, so data should be not found. I found different values in the response of TS-MRANGE depending on which docker image release I use:

**Initial Data:**

```
127.0.0.1:6379[15]> TS.CREATE multirange3 LABELS sensor 2 sensor 3
OK
127.0.0.1:6379[15]> keys *
1) "multirange3"

127.0.0.1:6379[15]> TS.ADD multirange3 1577210400000 20
(integer) 1577210400000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210401000 21
(integer) 1577210401000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210402000 22
(integer) 1577210402000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210403000 23
(integer) 1577210403000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210404000 24
(integer) 1577210404000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210405000 25
(integer) 1577210405000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210406000 26
(integer) 1577210406000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210407000 27
(integer) 1577210407000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210408000 28
(integer) 1577210408000

127.0.0.1:6379[15]> TS.ADD multirange3 1577210409000 29
(integer) 1577210409000
```
Responses that I get depending on the release:

**redislabs/redistimeseries:1.2.0**

```
127.0.0.1:6379[15]> TS.MRANGE 1580999664132 1580999674132 AGGREGATION avg 5000 FILTER sensor=3
1) 1) "multirange3"
   2) (empty list or set)
   3) 1) 1) (integer) 0
         2) "-nan"
```

**redislabs/redistimeseries:1.2.1**

```
127.0.0.1:6379[15]> TS.MRANGE 1580999664132 1580999674132 AGGREGATION avg 5000 FILTER sensor=3
1) 1) "multirange3"
   2) (empty list or set)
   3) 1) 1) (integer) 1577210400000
         2) "0"
```
The timestamp returned matches with the first timestamp found in the time-series

**redislabs/redistimeseries:1.2.2**

```
127.0.0.1:6379[15]> TS.MRANGE 1580999664132 1580999674132 AGGREGATION avg 5000 FILTER sensor=3
1) 1) "multirange3"
   2) (empty list or set)
   3) 1) 1) (integer) 1580999664132
         2) "0"
```
The timestamp returned matches with the initial timestamp range used in the query (TS.MRANGE)

**redislabs/redistimeseries:1.2.3** (same as 1.2.1 above)

```
127.0.0.1:6379[15]> TS.MRANGE 1580999664132 1580999674132 AGGREGATION avg 5000 FILTER sensor=3
1) 1) "multirange3"
   2) (empty list or set)
   3) 1) 1) (integer) 1577210400000
         2) "0"
```

**redislabs/redistimeseries:edge**

```
127.0.0.1:6379[15]> TS.MRANGE 1580999664132 1580999674132 AGGREGATION avg 5000 FILTER sensor=3
1) 1) "multirange3"
   2) (empty list or set)
   3) (empty list or set)
```

And IMHO this last response for `edge` image should be the right one since if no values are found in the MRANGE query, an empty array should be returned.

Anyway, my question: those different responses I get for each release happen randomly or are you changing the response in each release? If they are not random, the response coming from `edge` image will be the final response definitely for this use case in the next stable image?

**Comment by ashtul** [comment]
@averias 
Thank you for the feedback.
This was corrected and will be avoided as much as possible in the future.
