### ISSUE TITLE
Modify previous value

### ISSUE THREAD

**Issue by wenq1** [RedisTimeSeries/RedisTimeSeries#347]
Is it possible to modify the value of a given timestamp existing previously?

Use case is as follows: each time a failure event is triggered, we use TS.ADD 1 to mark, hence the data sequence is something like:

1581603670000:  1
1581603671000:  1
1581603672000:  1

And we calculate in real-time how many failures are there in the past 1 minute. In the above case, in the past 1 minute, the failure count is 3.

Sometimes, however, we need to modify the value at (say, 1581603670000) as the failure has gone, data should be like:

1581603670000:  0  (changed from 1)
1581603671000:  1
1581603672000:  1

And in the past 1 minute, the failure count should reduce to 0. Will that be possible?

**Comment by gkorland** [comment]
RedisTimeSeries doesn't support past events modification, but perhaps you can add another event that will represent an failure has gone.
e.g.

 1581603674000: -1
