### ISSUE TITLE
Question Only

### ISSUE THREAD

**Issue by gmonk** [RedisTimeSeries/RedisTimeSeries#348]
Greetings, 

I'm trying to see if RedisTimeSeries would be a good option for the TS data that I am currently working with. The Current data is being stored in MSSQL which does not seem efficient since it is clearly time series data .  But it does not seem like the typical time series data as there are multiple events that can happen per timestamp that need to be logged.  The data is logged every 100ms  and several things can and do happen all in the same timestamp.  Example listed below.  The first column is the TS the second is an event code and third is a parameter for that event code. As you can see multiple event codes can be produces within the same stamp.

02/03/2020 16:00:11.0 | 8 | 5 |  
02/03/2020 16:00:11.0 | 81 | 24 |  
02/03/2020 16:00:11.0 | 6 | 5 |  
02/03/2020 16:00:11.3 | 82 | 2 |  
02/03/2020 16:00:11.3 | 43 | 5 |  
02/03/2020 16:00:11.4 | 82 | 21 |  
02/03/2020 16:00:12.3 | 81 | 19 |  
02/03/2020 16:00:12.3 | 82 | 28 |  
02/03/2020 16:00:13.0 | 10 | 1 |  
02/03/2020 16:00:13.0 | 9 | 1 |  
02/03/2020 16:00:13.1 | 81 | 21 |  
02/03/2020 16:00:13.8 | 81 | 11 |  
02/03/2020 16:00:13.8 | 81 | 28 |  
02/03/2020 16:00:13.8 | 44 | 1 |  
02/03/2020 16:00:14.0 | 0 | 2 |  
02/03/2020 16:00:14.0 | 11 | 1 |  
02/03/2020 16:00:14.0 | 1 | 2 |  
02/03/2020 16:00:14.0 | 2 | 3 |  
02/03/2020 16:00:14.0 | 2 | 4 |  
02/03/2020 16:00:14.0 | 2 | 6 |  
02/03/2020 16:00:14.0 | 2 | 7 |  
02/03/2020 16:00:14.0 | 2 | 8 |

**Comment by gkorland** [comment]
It seems like breaking each column to a different series might be the right solution in your case.
```
02/03/2020 16:00:11.0 | 8 | 5 |  
```
Should be:

```
TS.MADD ts:1 1580738411000 8 ts:2 1580738411000 5
```

**Comment by gmonk** [comment]
Thanks for the info. I will give it a try
