### ISSUE TITLE
 [Help] Wanted  clarification for using this module

### ISSUE THREAD

**Issue by SchedulerSimulator** [RedisTimeSeries/RedisTimeSeries#365]
I want to use this module for storing network link metrics in redis. I have the following questions for which I didn't find answers in the official release: 

Q. What is the max number of labels which can be added?

Q. What is the max size of keys which is supported? I am intending to keep metric:link-name as key. Here since we identify link names by 6 tuple (source zone, destination zone, source device, destination device, source interface, destination interface), key size can be longer. So how much is the recommended key size/length limit?
Example for one key: in_error_count:hyd01:maa01:q3-p1.hyd01:sp8.hyd01:Ethernet32/1:Ethernet5/18/1

Q. What is the max number of keys or time series which can be present?

Please help.

**Comment by ashtul** [comment]
Thank you for the inquiry.

> Q. What is the max number of labels which can be added?


A. There is no hard limit but you might experience some performance degradation when querying a  very large number of labels.

> Q. What is the max size of keys which is supported? I am intending to keep metric:link-name as key. Here since we identify link names by 6 tuple (source zone, destination zone, source device, destination device, source interface, destination interface), key size can be longer. So how much is the recommended key size/length limit?
> Example for one key: in_error_count:hyd01:maa01:q3-p1.hyd01:sp8.hyd01:Ethernet32/1:Ethernet5/18/1

A. There is no limit as long as you have memory available for the module. We would recommend downsampling your data and retire raw data by using the RETENTION option.
We have recently added data compression to the module which reduces memory footprint significantly.

> Q. What is the max number of keys or time series which can be present?


A. There is no limit beyond the usual limits on Redis itself.

**Comment by SchedulerSimulator** [comment]
@ashtul thanks a lot for the quick reply. 
We are also intending to keep data for 2 days at least. Is there any limit on retention period?

**Comment by ashtul** [comment]
@SchedulerSimulator 
No, there is no limit on retention time. Just retention is milliseconds as well.

**Comment by SchedulerSimulator** [comment]
Also, can labels have json values? I have a use-case where data points of a single key can have different values for same label name. 
An alternative will be to have unique keys for each unique combination of labels. This usecase is blocking me from using this module. Can you please suggest what can be done in such cases.

For example, for one link link-1, metric latency, the datapoints can come with a label called linkStatus, like the following:
key: latency:link-1
value: 25
label: linkStatus=true (for link up) / false (for link down)
How can I model such case. It is required for further processing and showing on dashboard.

**Comment by danni-m** [comment]
@SchedulerSimulator Labels are meant for metadata, adding per timestamp label is not currently supported.
What you can do is to split it to a different TS Key and use 1 and 0 for true and false.
