### ISSUE TITLE
Does RedisTimeSeries support Redis Cluster?

### ISSUE THREAD

**Issue by pvtpogopuschel** [RedisTimeSeries/RedisTimeSeries#368]
Hello RedisTimeSeries team,

Thank you so much for building such a blazing fast and solid time series module for redis. We are using it very actively and are looking forward to further expand its usage within our application.

However, a very important question has crossed my mind a few times. Has anybody tried using the module with redis cluster so far? I have read of several other redis modules that have issues running in a cluster environment and I am a bit uncertain on whether this might affect this time series module as well.

Thank you!

**Comment by gkorland** [comment]
RedisTimeSeries supports Redis Cluster and should run without any issues. If you encounter any issues please report. We at Redis Labs are testing it regularly on Redis Enterprise cluster.

**Comment by pvtpogopuschel** [comment]
Perfect, thanks, @gkorland! I can reopen the issue if questions arise :)

**Comment by gkorland** [comment]
With one exception (thanks to @danni-m for remind me) TS.MGET & TS.MRANGE can't work on keys that are cross slot

**Comment by pvtpogopuschel** [comment]
Makes sense! Thanks for pointing that out

**Comment by afarber** [comment]
What about TimeSeries + OSS Cluster please? We have selected it for Azure Enterprise E10 and our app has problems to connect after few hours
