### ISSUE TITLE
Assertion failed: leading + blocksize <= BINW (gorilla.c: readFloat: 441) on 32bit system

### ISSUE THREAD

**Issue by frahubdev** [RedisTimeSeries/RedisTimeSeries#370]
System: 

# server |  
-- | --
Redis version | 5.0.8
Redis git sha1 | 00000000
Redis git dirty | 0
Redis build | 194dd742fd55eb79
Redis mode | standalone
Os | Linux 4.19.75-v7+ armv7l
Arch bits | 32
Multiplexing api | epoll
Atomicvar api | atomic-builtin
Gcc version | 9.2.0
Process | 1
Run | ca34b6cd6a4c964bea88bc9161aa6885099de65a
Tcp port | 6379
Uptime in seconds | 3364
Uptime in days | 0
Hz | 10
Configured hz | 10
Lru clock | 9289728
Executable | /data/redis-server
Config file |  
  |  
# clients |  
Connected clients | 14
Client recent max input buffer | 4
Client recent max output buffer | 0
Blocked clients | 0
  |  
# memory |  
Used memory | 1079984
Used memory human | 1.03M
Used memory rss | 2715648
Used memory rss human | 2.59M
Used memory peak | 1271920
Used memory peak human | 1.21M
Used memory peak perc | 84.91%
Used memory overhead | 924028
Used memory startup | 652056
Used memory dataset | 155956
Used memory dataset perc | 36.44%
Allocator allocated | 1129464
Allocator active | 1544192
Allocator resident | 2076672
Total system memory | 1023012864
Total system memory human | 975.62M
Used memory lua | 27648
Used memory lua human | 27.00K
Used memory scripts | 0
Used memory scripts human | 0B
Number of cached scripts | 0
Maxmemory | 3221225472
Maxmemory human | 3.00G
Maxmemory policy | noeviction
Allocator frag ratio | 1.37
Allocator frag bytes | 414728
Allocator rss ratio | 1.34
Allocator rss bytes | 532480
Rss overhead ratio | 1.31
Rss overhead bytes | 638976
Mem fragmentation ratio | 2.62
Mem fragmentation bytes | 1677664
Mem not counted for evict | 2870
Mem replication backlog | 0
Mem clients slaves | 0
Mem clients normal | 268002
Mem aof buffer | 2870
Mem allocator | jemalloc-5.1.0
Active defrag running | 0
Lazyfree pending objects | 0
  |  
# persistence |  
Loading | 0
Rdb changes since last save | 111202
Rdb bgsave in progress | 0
Rdb last save time | 1586344668
Rdb last bgsave status | ok
Rdb last bgsave time sec | -1
Rdb current bgsave time sec | -1
Rdb last cow size | 0
Aof enabled | 1
Aof rewrite in progress | 0
Aof rewrite scheduled | 0
Aof last rewrite time sec | -1
Aof current rewrite time sec | -1
Aof last bgrewrite status | ok
Aof last write status | ok
Aof last cow size | 0
Aof current size | 25832442
Aof base size | 21303964
Aof pending rewrite | 0
Aof buffer length | 0
Aof rewrite buffer length | 0
Aof pending bio fsync | 0
Aof delayed fsync | 0
  |  
# stats |  
Total connections received | 20
Total commands processed | 48692
Instantaneous ops per sec | 9
Total net input bytes | 9076634
Total net output bytes | 6361619
Instantaneous input kbps | 0.53
Instantaneous output kbps | 5.25
Rejected connections | 0
Sync full | 0
Sync partial ok | 0
Sync partial err | 0
Expired keys | 0
Expired stale perc | 0.00
Expired time cap reached count | 0
Evicted keys | 0
Keyspace hits | 14787
Keyspace misses | 373
Pubsub channels | 1
Pubsub patterns | 0
Latest fork usec | 0
Migrate cached sockets | 0
Slave expires tracked keys | 0
Active defrag hits | 0
Active defrag misses | 0
Active defrag key hits | 0
Active defrag key misses | 0
  |  
# replication |  
Role | master
Connected slaves | 0
Master replid | 238760a33225060a1b26536bcab14dbae937972e
Master replid2 | 0000000000000000000000000000000000000000
Master repl offset | 0
Second repl offset | -1
Repl backlog active | 0
Repl backlog size | 1048576
Repl backlog first byte offset | 0
Repl backlog histlen | 0
  |  
# cpu |  
Used cpu sys | 17.921017
Used cpu user | 13.817709
Used cpu sys children | 0.000000
Used cpu user children | 0.002137
  |  
# cluster |  
Cluster enabled | 0
  |  
# keyspace |  
Db0 | keys=27,expires=0,avg_ttl=0

RedisTimesSeries Version: commit d2b82cedd94642c9581566e1d2c2c7687a4e9a44

EXAMPLE_KEY: 

```sh
ts.info EXAMPLE_KEY
```

result:

```
1) "totalSamples"
2) 1985
3) "memoryUsage"
4) 4180
5) "firstTimestamp"
6) 1586328564
7) "lastTimestamp"
8) 1586348318
9) "retentionTime"
10) 3600
11) "chunkCount"
12) 1
13) "maxSamplesPerChunk"
14) 256
15) "labels"
16) []
17) "sourceKey"
18) null
19) "rules"
20) []
```

Get RANGE from EXAMPLE_KEY:

```sh
ts.range EXAMPLE_KEY- + aggregation avg 900
```

result, redis-server halted:

```sh
1:C 08 Apr 2020 10:14:11.218 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 08 Apr 2020 10:14:11.218 # Redis version=5.0.8, bits=32, commit=00000000, modified=0, pid=1, just started
1:C 08 Apr 2020 10:14:11.219 # Configuration loaded
1:M 08 Apr 2020 10:14:11.236 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
1:M 08 Apr 2020 10:14:11.237 * Running mode=standalone, port=6379.
1:M 08 Apr 2020 10:14:11.237 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 08 Apr 2020 10:14:11.237 # Server initialized
1:M 08 Apr 2020 10:14:11.238 * Module 'timeseries' loaded from /usr/lib/redis/modules/redistimeseries.so
1:M 08 Apr 2020 10:14:12.934 * DB loaded from append only file: 1.695 seconds
1:M 08 Apr 2020 10:14:12.934 * Ready to accept connections
Assertion failed: leading + blocksize <= BINW (gorilla.c: readFloat: 441)
```

But in some cases, the command works, the result of the command is like...

```
1) [1586344500,"106.965721"]
2) [1586345400,"106.96572100000002"]
3) [1586346300,"106.96572100000002"]
4) [1586347200,"106.96572100000002"]
5) [1586348100,"106.96572100000002"]
```

Unfortunately, with an AOF enabled the redis-server will come in a endless loop, cause of the last command which will bring the server down.

**Comment by danni-m** [comment]
@frahubdev can you share the inserted data?

**Comment by ashtul** [comment]
@frahubdev this is likely related to PR #359 
Are you using the latest image?
Please try the newest version to see if issue persists.

**Comment by frahubdev** [comment]
@danni-m 
the inserted data like this:

"TS.ADD" "EXAMPLE_KEY" "1586352834" "0.0"
"TS.ADD" "EXAMPLE_KEY" "1586352834" "0.0"

**Comment by frahubdev** [comment]
@danni-m the inserted Data are very simpel like this:

"TS.ADD" "EXAMPLE_KEY" "1586352834" "104.1202"
"TS.ADD" "EXAMPLE_KEY" "1586352834" "73.557404"
"TS.ADD" "EXAMPLE_KEY" "1586352834" "235.709366"

do you whish a aof file or an "export" of the data?
should i check the length of the values(floats)?

@ashtul  yes it sounds like PR #359

i had compiled the redistimeseries.so from:

commit d2b82cedd94642c9581566e1d2c2c7687a4e9a44
Author: Guy Korland <gkorland@gmail.com>
Date:   Tue Mar 31 12:45:18 2020 +0300

and i used the offical docker image redis:latest (5.0.8)

**Comment by frahubdev** [comment]
I have build it again and test it with another docker image: redisfab/redis-arm32v7-buster-xbuild:5.0.5

Now i get another failure:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 09 Apr 2020 07:56:01.338 # Redis 5.0.5 crashed by signal: 11
1:M 09 Apr 2020 07:56:01.338 # Crashed running the instruction at: 0x76d84072
1:M 09 Apr 2020 07:56:01.338 # Accessing address: 0x30a64a3c
1:M 09 Apr 2020 07:56:01.338 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/arm-linux-gnueabihf/libc.so.6(malloc_usable_size+0x31)[0x76d84072]

Backtrace:
redis-server *:6379(logStackTrace+0x27)[0x47beb4]
redis-server *:6379(sigsegvHandler+0x6b)[0x47c3b4]
/lib/arm-linux-gnueabihf/libc.so.6(+0x25cb0)[0x76d52cb0]

------ INFO OUTPUT ------
# Server
redis_version:5.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:3824e691fad72eec
redis_mode:standalone
os:Linux 4.19.75-v7+ armv7l
arch_bits:32
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:d41b737854a91a5f1d69c5d2b4d2179027e1e9b3
tcp_port:6379
uptime_in_seconds:0
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:9360657
executable:/data/redis-server
config_file:

# Clients
connected_clients:1
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:725544
used_memory_human:708.54K
used_memory_rss:0
used_memory_rss_human:0B
used_memory_peak:725544
used_memory_peak_human:708.54K
used_memory_peak_perc:100.01%
used_memory_overhead:655138
used_memory_startup:604464
used_memory_dataset:70406
used_memory_dataset_perc:58.15%
allocator_allocated:0
allocator_active:0
allocator_resident:0
total_system_memory:1023012864
total_system_memory_human:975.62M
used_memory_lua:27648
used_memory_lua_human:27.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:3221225472
maxmemory_human:3.00G
maxmemory_policy:noeviction
allocator_frag_ratio:nan
allocator_frag_bytes:0
allocator_rss_ratio:nan
allocator_rss_bytes:0
rss_overhead_ratio:nan
rss_overhead_bytes:0
mem_fragmentation_ratio:nan
mem_fragmentation_bytes:0
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:49574
mem_aof_buffer:0
mem_allocator:libc
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:1
rdb_changes_since_last_save:23915
rdb_bgsave_in_progress:0
rdb_last_save_time:1586418961
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
loading_start_time:1586418961
loading_total_bytes:6483688
loading_loaded_bytes:5811758
loading_loaded_perc:89.64
loading_eta_seconds:1

# Stats
total_connections_received:1
total_commands_processed:1
instantaneous_ops_per_sec:0
total_net_input_bytes:14
total_net_output_bytes:3350
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:ff343bb56da034fc6b1229ef850d37043e5633bc
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.029898
used_cpu_user:0.328885
used_cpu_sys_children:0.000000
used_cpu_user_children:0.005144

# Commandstats
cmdstat_info:calls=1,usec=209,usec_per_call=209.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=27,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=3 addr=172.19.0.9:36340 fd=10 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=info

------ REGISTERS ------

------ FAST MEMORY TEST ------
1:M 09 Apr 2020 07:56:01.343 # Bio thread for job type #0 terminated
1:M 09 Apr 2020 07:56:01.343 # Bio thread for job type #1 terminated
1:M 09 Apr 2020 07:56:01.343 # Bio thread for job type #2 terminated
*** Preparing to test memory region 4f5000 (49152 bytes)
*** Preparing to test memory region a2e000 (569344 bytes)
*** Preparing to test memory region 754db000 (8388608 bytes)
*** Preparing to test memory region 75cdc000 (8388608 bytes)
*** Preparing to test memory region 764dd000 (8716288 bytes)
*** Preparing to test memory region 76e24000 (12288 bytes)
*** Preparing to test memory region 76e4a000 (8192 bytes)
*** Preparing to test memory region 76e8b000 (4096 bytes)
*** Preparing to test memory region 76f52000 (8192 bytes)
*** Preparing to test memory region 76f56000 (8192 bytes)
.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: malloc_usable_size (base: 0x76d84041)
Module: /lib/arm-linux-gnueabihf/libc.so.6 (base 0x76d2d000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x76d84041 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
1:M 09 Apr 2020 07:56:03.687 # dump of function (hexdump of 177 bytes):
b12049a0f1080238b5794450f8043c8c6a03f0020523f00703012c12d03db1886882420ad3c9688a4207d2181f38bd1a44506810f00100f8d138bda3f1080038bd7047d40a581e84ead204e4b2012c08bf0224002d14bf002304231844135ca34208d04bb103f10801814205d8c01a135ca342f6d1083838bd03487844fbf779fc00bfe2060a00d4340800304b31497b44314a2de9f0477a4453f801808cb0136c0746d8f80020002b0b924adb01ad2822

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by ashtul** [comment]
@frahubdev if you can provide an AOF it will be great.

I see you are using a 32bit image.
Can you see if the issue persists on 64-bit system?

**Comment by frahubdev** [comment]
@ashtul yes, i will give a try to 64-bit system.

**Comment by gkorland** [comment]
@frahubdev did you try it on 64bit?

**Comment by danni-m** [comment]
@frahubdev please reopen if you still experience this issue.
