### ISSUE TITLE
Crash on incomplete TS.RANGE query due to parseCountArgument

### ISSUE THREAD

**Issue by alesvaupotic** [RedisTimeSeries/RedisTimeSeries#373]
Hi, guys,

will somebody please confirm a crash for me? I pressed Enter too soon today on some queries and finally got this repeatable crash:
```
docker run -p 6379:6379 -it --rm redislabs/redistimeseries
redis-cli
ts.create s1:0:0 retention 2592000 
ts.range s1:0:0 - + count 
```
If not confirmed, I'll append the logs.

Thanks!

**Comment by filipecosta90** [comment]
hi there @alesvaupotic, you're absolutely right. 
It's crashing due to the fact that we're only checking if COUNT is in the right position but not ensuring that there is an argument to call `RedisModule_StringToLongLong(argv[offset + 1], count)`.

**Comment by alesvaupotic** [comment]
Thanks for quick confirmation. I'll manage in the meantime but looking forward to the fix.

**Comment by filipecosta90** [comment]
hi there @alesvaupotic , the fix has been merged :)

**Comment by alesvaupotic** [comment]
Thanks so much. Keep up the good work, TimesSeries is awesome.
