### ISSUE TITLE
TS.Mrange giving less data than the actual

### ISSUE THREAD

**Issue by SchedulerSimulator** [RedisTimeSeries/RedisTimeSeries#379]
I am using TS.Mrange with filters to get past 1 day's data across different keys at regular interval of time (every 5 min). 
But I see at least once in a day I get less data than the usual (count of data fetched is less than it should be). I am unable to understand why this could be happening. Is there any logs which I can check for this? Or any pointers why this could be happening?

**Comment by ashtul** [comment]
@SchedulerSimulator 
Can you provide more details? which version are you using? Have you upgraded recently? Have you introduced any changes to your program logic or you just haven't tested for it before?
What queries are you running and at what time are the changes?
It may be related to case #376 which I'm currently investigating.

**Comment by ashtul** [comment]
@SchedulerSimulator Can you check if PR #380 fixed the issue?

**Comment by SchedulerSimulator** [comment]
> which version are you using?
redis_version:5.0.7

> Have you upgraded recently?
No

> Have you introduced any changes to your program logic or you just haven't tested for it before?
No, I didn't make any changes to program logic. So, we store network link metrics in timeseries. Every 5 minutes, we query past 1 day's data a particular metric (so after one day the number of values for a metric are same since network infra doesn't change). I am seeing at least once in a day, my application gets less number of values from timeseries than other instants. Exact same command is issued every 5 minutes. 

> What queries are you running
The queries are similar to the following with more filters and getting past 1 days data
_ts.mrange 1588255536 1588255836 withlabels filter metricName=link_availability_

> at what time are the changes
There is no change on the application side when this issue is encountered.

**Comment by SchedulerSimulator** [comment]
I don't see anything in redis logs as well. Where can I check the logs?

**Comment by ashtul** [comment]
@SchedulerSimulator

**Comment by SchedulerSimulator** [comment]
So looking at past 1 weeks data, I am seeing this occurrence once every day. Why could this be happening?

**Comment by danni-m** [comment]
@SchedulerSimulator Is this still an issue?

**Comment by danni-m** [comment]
@SchedulerSimulator im closing this ticket, please reopen if you sill have issues.
