### ISSUE TITLE
TS.MADD error when adding multiple values with automatic timestamp

### ISSUE THREAD

**Issue by dzunk** [RedisTimeSeries/RedisTimeSeries#426]
I'm working on a [Ruby adapter](https://github.com/dzunk/redis-time-series) for this module, and came across this issue implementing the `TS.MADD` command.

The [docs for TS.MADD](https://oss.redislabs.com/redistimeseries/commands/#tsmadd) indicate "* can be used for automatic timestamp". When adding multiple values to a single series with automatic timestamp, only the first one is added, and the remaining values raise a command error.
```ruby
[1] pry(main)> @ts1.madd 2, 4, 5
DEBUG: TS.MADD foo * 2 foo * 4 foo * 5
=> [1592168332102,
 #<Redis::CommandError: TSDB: Timestamp cannot be older than the latest timestamp in the time series>,
 #<Redis::CommandError: TSDB: Timestamp cannot be older than the latest timestamp in the time series>]
```
Same behavior from `redis-cli`:
```
127.0.0.1:6379> TS.MADD foo * 2 foo * 4 foo * 5 foo * 6
1) (integer) 1592168764455
2) (error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
3) (error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
4) (error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
```
Works as expected with explicit timestamps:
```
127.0.0.1:6379> TS.MADD foo 1592168764456 2 foo 1592168764457 4 foo 1592168764458 6
1) (integer) 1592168764456
2) (integer) 1592168764457
3) (integer) 1592168764458
```
I did find #195 which sounds similar, and I am running in Docker on MacOS, so not 100% if it's an issue with my OS or not. I figured that since it's a single command, clock drift over time probably isn't causing this. Also, it might just be an unsupported use case to add multiple values with automatic timestamp, in which case the docs could be updated to indicate this. Thoughts?

**Comment by gkorland** [comment]
The current version supports "append-only" mode. Meaning, two values can't have the same timestamp. The following PR is going to add this support, https://github.com/RedisTimeSeries/RedisTimeSeries/pull/413. 

Notice, adding support for "out of order" mode in our example will probably result in 6 override the other values at the same timestamp.

**Comment by dzunk** [comment]
Makes sense. I was imagining it might internally increment the timestamp for each value by 1ms, so `foo * 2 foo * 3 foo * 4` might wind up with `1592168764456`, `1592168764457`, `1592168764458` timestamps. If it's unsupported behavior though, I can make the adapter not accept multiple values for a single series like that, or automatically inject the timestamp(s). Thanks very much for the quick response!
