### ISSUE TITLE
[Need Help Reproducing] Race Condition? TSDB: Timestamp cannot be older than the latest timestamp

### ISSUE THREAD

**Issue by eadz** [RedisTimeSeries/RedisTimeSeries#432]
I cannot reproduce this issue with redis-cli, but I'm pretty sure it's a race condition with RedisTimeSeries.

The  code I have below produces this in the `redis-cli monitor` logs, and then the error below

```
1592393361.441723 [0 127.0.0.1:59952] "TS.CREATE" "e8acd"
1592393361.441932 [0 127.0.0.1:59952] "TS.ADD" "e8acd" "*" "15"
1592393361.442113 [0 127.0.0.1:59952] "TS.ADD" "e8acd" "*" "15"
1592393361.442302 [0 127.0.0.1:59952] "TS.ADD" "e8acd" "*" "15"
```
Error:

`TSDB: Timestamp cannot be older than the latest timestamp in the time series (Redis::CommandError)`

```ruby
require 'bundler/inline'
require 'bundler'
Bundler.configure
require 'redis'

key = (rand * 2**20).to_i.to_s(16)
puts "key: #{key}"
Redis.current.call(["TS.CREATE", key])
300.times do
  Redis.current.call(["TS.ADD", key, "*", "15"])
end
```

Obviously I'm not setting the timestamp, so I can't see how this can be anything other than a bug in RedisTimeSeries.

**Comment by ashtul** [comment]
@eadz 
The module does not support doubles as timestamps and therefore all your timestamps overlap one another. Are you attempting to submit nanoseconds as timestamps?

**Comment by eadz** [comment]
Looking at the code, it seems the timestamps can't be equal?

` if (timestamp <= series->lastTimestamp && series->lastTimestamp != 0)`

https://github.com/RedisTimeSeries/RedisTimeSeries/blob/61fb8252e42420060ce9840183fd9049ac89d3f2/src/tsdb.c#L219

**Comment by eadz** [comment]
@ashtul as you can see from the `redis-cli monitor` output, I'm simply using `*` as my timestamp.

**Comment by danni-m** [comment]
@eadz its a known issue, when you use `*` you get the current epoch timestamp (in milliseconds), when redis receives multiple requests in the same milliseconds it will raise an error due to the fact that we do not support overwriting samples or sending samples to an older timestamp.
Having said that, we are working on this and it will be resolved in the coming releases.

**Comment by eadz** [comment]
Thanks @danni-m

**Comment by danni-m** [comment]
Closing as a dup of 333

**Comment by danni-m** [comment]
https://github.com/RedisTimeSeries/RedisTimeSeries/issues/333
