### ISSUE TITLE
Negative timestamps not working as expected

### ISSUE THREAD

**Issue by shaunsales** [RedisTimeSeries/RedisTimeSeries#434]
If we want to represent a timestamp older than UNIX Epoch, we need to use a timestamp with a negative value. However upon entering a negative value, no other timestamp values can be added after.

```
>> ts.create test
"OK"
>> ts.add test -1 1
(integer) -1
>> ts.add test -2 1
(error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
>> ts.add test 2 1
(error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
```

I think one of two things should happen;
1) Reject any negative value for timestamps, or
2) After adding a negative timestamp, any "newer" timestamp should be accepted

I would also suggest there should be some clear min max values on timestamps that are given to users - i.e. "timestamp cannot be older/newer than N and must be in UNIX Epoch milliseconds". 

Thanks,
Shaun

**Comment by danni-m** [comment]
@shaunsales we need to block any negative timestamps, do you have a use-case for using them?

**Comment by shaunsales** [comment]
@danni-m The .NET `DateTime` range includes negative numbers when converted to Unix Epoch time. I don't think we should necessarily support negative numbers, but at least an error should be thrown.

**Comment by danni-m** [comment]
@shaunsales closing this as we now block any negative timestamp on insertion.
