### ISSUE TITLE
Memory usage after redis restart is half from before

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/RedisTimeSeries#45]
MOD-152

Steps:
1. Put 1.51 million keys.
The memory usage will be around 17GB.
2. Enable aof 
3. Restart the shard.
When the shard will restart and load from aof the used memory is less than 8gb.

**Comment by danni-m** [comment]
fixed in
https://github.com/RedisTimeSeries/RedisTimeSeries/pull/157
