### ISSUE TITLE
Calling TS.RANGE yields "0" even when there is no data

### ISSUE THREAD

**Issue by Curclamas** [RedisTimeSeries/RedisTimeSeries#464]
### Observed

When trying to get an aggregated value (e.g. MAX, AVG) from a range where there are no samples stored in the database, `0` is returned as resulting value.

### Expected

There would be different ways to handle this (empty array, `NaN`, exception etc.). Getting a successful result of `0` is certainly (at least for me) not expected behavior.

### Reproduce

Try to run this on a range that does not contain any samples:

```
TS.RANGE temperature:3:32 1548149200000 1548149210000 AGGREGATION avg 10000
```

### Background

I have had a brief look on how aggregation / compaction is handled and it seems like singe value contexts and avg contexts are initialized with 0:

https://github.com/RedisTimeSeries/RedisTimeSeries/blob/6102a1ae6d29eb5ca23900cc88a131e529586a68/src/compaction.c#L41
https://github.com/RedisTimeSeries/RedisTimeSeries/blob/6102a1ae6d29eb5ca23900cc88a131e529586a68/src/compaction.c#L70

Especially when looking at the finalization part of AVG it becomes clear that the developers have thought of a case where count is 0 to prevent illegal zero division:

https://github.com/RedisTimeSeries/RedisTimeSeries/blob/6102a1ae6d29eb5ca23900cc88a131e529586a68/src/compaction.c#L82-L83

I am not sure how the intended result could look like. My gut feeling says we should either return `NaN` or `[ ]` because returning just `0` would be misleading in many cases, think of returning the average balance of a bank account or the temperature of a fridge -> here `0` does have a distinct meaning, but only if we have samples yield this value.
What's your idea how to implement this with minimal overhead and minimal breaking changes? 

Right now in my code I have to do now some sort of pre-flight-check with COUNT before performing any aggregations, which is wasting alot of resources...

**Comment by ashtul** [comment]
@danni-m should we initialized `doubles` with `NAN` then use the `isnan` function to check if they were changed?

**Comment by danni-m** [comment]
@ashtul i think it depends on the aggregation, for some of them, `0` is the right response (for example: count).
we probably need to implement it per aggregation, I don't see what we can apply that will always make sense.

**Comment by Curclamas** [comment]
@danni-m @ashtul thx for looking into the issue!
I have looked a little into the actual code and think there would be multiple ways to implement it.

However from what I have seen, `count` would be the only case where `0` is actually meaningful. For all others, especially arithmetic ones, `NaN` would be more precise. First/Last would be a case where also an empty array could make sense. But also there `NaN` is more meaningful than `0`.

As of my knowledge `NaN` is no normally allowed value in redis time series? That way it would be always distinguishable.
