### ISSUE TITLE
CREATERULE after data has been created

### ISSUE THREAD

**Issue by lepe** [RedisTimeSeries/RedisTimeSeries#472]
According to #364 , rules need to be created before inserting data (but I couldn't find that in the documentation). 

I have a series with hundreds of millions of records and I would like to create a rule to compact results. How can I do that without copying all the data again? 
If there is no easy way to do it, can that functionality be added (perhaps populate the aggregation when there is already data in a key)?

**Comment by gkorland** [comment]
@lepe is on our road map, there is no build in solution.
Duplicate #76

**Comment by lepe** [comment]
Good to know. Thanks

**Comment by K-Jo** [comment]
@gkorland @lepe https://github.com/RedisTimeSeries/RedisTimeSeries/pull/474
