### ISSUE TITLE
Build fails - BINDIR is undefined

### ISSUE THREAD

**Issue by JoelBender** [RedisTimeSeries/RedisTimeSeries#480]
I'm attempting to build the module and install it into Redis server version 6.0.5.

 > $ git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git
> $ cd RedisTimeSeries/
> $ make setup
> deps/readies/mk/main:23: *** It seems build prerequisites have not been installed: please run 'sudo make setup'..  Stop.

Ok.

> $ sudo make setup
> deps/readies/mk/main:23: *** It seems build prerequisites have not been installed: please run 'sudo make setup'..  Stop.

Strange, but there is an equivalent:

> $ sudo python3 system-setup.py 
> apt-get -qq update -y
> /usr/bin/python3 -m pip --version
> pip 20.1.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
> /usr/bin/python3 -m pip install --disable-pip-version-check wheel
> /usr/bin/python3 -m pip install --disable-pip-version-check setuptools --upgrade
> apt-get -qq install -y git jq curl
> apt-get -qq install -y build-essential
> apt-get -qq install -y lcov
> /usr/bin/python3 -m pip install --disable-pip-version-check -r tests/requirements.txt
> /usr/bin/python3 -m pip install --disable-pip-version-check jinja2

Seems to be fine.

> $ make build
> deps/readies/mk/bindirs.rules:5: *** BINDIR is undefined.  Stop.

Fails.  More info:

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04 LTS
> Release:	20.04
> Codename:	focal

> $ make --version
> GNU Make 4.2.1
> Built for x86_64-pc-linux-gnu

> $ gcc --version
> gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

> $ python3 --version
> Python 3.8.2

> $ redis-server --version
> Redis server v=6.0.5 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=28cf99ea82a58383

**Comment by danni-m** [comment]
@rafie can you take a look please?

**Comment by danni-m** [comment]
@JoelBender in the meantime you can use the docker image to run redis with the module preloaded.

**Comment by rafie** [comment]
Please note that RedisTimeSeries uses Python 2 for automation (that is, Python 2 needs to be available, and `make setup` indeed installs it). So if invoking `system-setup.py` directly, it should be either `./system-setup.py` or `python2 system-setup.py`.
It is also recommended running inside a Python virtual environment.
We'll soon be moving automation to Python 3.
The `make setup` machanism is indeed broken.
