### ISSUE TITLE
Add Duplicate timestamp policy on Create (PM-770)

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/RedisTimeSeries#521]
When a sample is added to a timeseries of which a sample already exists, we need a policy to handle this
Following should be added to TS.CREATE as feature options

`OVERRIDE_POLICY` with options:
   *  BLOCK (error)
   * MIN
   * MAX
   * LAST (default as it equals replace)
   * FIRST (ignore the new sample)

**Comment by filipecosta90** [comment]
@gkorland does it need to be on creation, or can it be on insertion like for example timescale with the `ON CONFLICT` [clause](https://docs.timescale.com/latest/using-timescaledb/writing-data)?:
> TimescaleDB supports UPSERTs in the same manner as PostgreSQL via the optional ON CONFLICT clause (PostgreSQL docs). If such a clause is provided, rather than cause an error, an inserted row that conflicts with another can either (a) do nothing or (b) result in a subsequent update of that existing row.

**Comment by K-Jo** [comment]
@filipecosta90 @gkorland @danni-m let's have latest discussion on PM-770

**Comment by dpipemazo** [comment]
@gkorland Thank you for working on this. 

One thing missing here from the discussion in #492 is a `SUM` option. Would the `SUM` be possible as well? This would be useful for counting things at potentially high frequency without missing data.

**Comment by danni-m** [comment]
@dpipemazo Your information on #492 really helps to understand your use-case, but im not sure this will solve it altogether.
What we are planning to do here is to take the raw data and aggregate it on insertion. this means we will agregate *once* and only once.

If you are reporting timing (in MS for example) and you aggregate using SUM, you will end up having the sum of all the timing without the knowledge of how many events were aggregated. To have the event count you will need to count the events in a different key.

**Comment by dpipemazo** [comment]
> If you are reporting timing (in MS for example) and you aggregate using SUM, you will end up having the sum of all the timing without the knowledge of how many events were aggregated. To have the event count you will need to count the events in a different key.

That's fine -- I won't use `SUM` for timing. I'll use something like `FIRST` or `LAST`.

I do want `SUM` for event counting and would indeed plan to do that on a different key. Thanks!
