### ISSUE TITLE
Duplicate rule for key

### ISSUE THREAD

**Issue by AlKorochkin** [RedisTimeSeries/RedisTimeSeries#527]
Hello,

**Versions**
```
# Server
redis_version:5.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:476a8034ec27f9ca
redis_mode:standalone
os:Linux 4.15.18-12-pve x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.3.0
```
I installed the module following **Build and Run it yourself** from readme. RedisTimeSeries version looks strange:
```
323:M 07 Sep 2020 07:40:18.807 * <timeseries> RedisTimeSeries version 999999, git_sha=cdcee019c0740ff795b984c8fdabbe4fed553ee6
323:M 07 Sep 2020 07:40:18.807 * <timeseries> Redis version found by RedisTimeSeries : 5.0.5 - oss
```

**Issue**

I noticed that the source key can contain duplicate of the same rules:
![series rule](https://user-images.githubusercontent.com/60496858/92369772-ddbbd000-f112-11ea-97f5-def87e600009.jpg)

Attempting to create a duplicate rule for a key usually produces error:
**_TSDB: the destination key already has a rule_**

But in my case, it will be possible to create a repeating rule once after restarting the machine. 
The next attempt will throw an error **_TSDB: the destination key already has a rule_**. 
Restart and I can create another duplicate.

I think that the process of Redis is not terminate correctly on my machine when I turn it off.
Maybe it somehow affects the rdb-file and RedisTimeSeries.

Please help me figure it out.

**Comment by danni-m** [comment]
Hi @AlKorochkin, this does seems like a real issue.

Can you provide the exact steps that got you to this situation?

**Comment by AlKorochkin** [comment]
**Initial state**
* redis-server stopped
* rdb-file deleted

**Reproducing steps**
1. start redis-server
2. connect by redis-cli
3. create source key:
`localhost:6379> TS.CREATE TestKey-1 LABELS type test`
`localhost:6379> OK`
4. add points into the series:
`localhost:6379> TS.ADD TestKey-1 * 1.0`
`localhost:6379> OK`
`localhost:6379> TS.ADD TestKey-1 * 1.1`
`localhost:6379> OK`
5. create dest key:
`localhost:6379> TS.CREATE TestKey-2 LABELS type test-dup-rul`
`localhost:6379> OK`
6. create rule:
`localhost:6379> TS.CREATERULE TestKey-1 TestKey-2 AGGREGATION last 60`
`localhost:6379> OK`
7. repeat creating previous rule:
`localhost:6379> TS.CREATERULE TestKey-1 TestKey-2 AGGREGATION last 60`
`localhost:6379> (error) ERR TSDB: the destination key already has a rule`
8. shutdown redis-server from cli and stop service:
`localhost:6379> SHUTDOWN`
`~# service redis-server stop`
9. start redis-server again:
`localhost:6379> service redis-server start`
10. connect by redis-cli and repeat creating rule:
`localhost:6379> TS.CREATERULE TestKey-1 TestKey-2 AGGREGATION last 60`
`localhost:6379> OK`
11. repeat step 7

Thus, RedistimeSeries allows me to create a duplicate rule every time after restarting Redis.

Log from cli:
* [cli.log](https://github.com/RedisTimeSeries/RedisTimeSeries/files/5187583/cli.log)

**Comment by AlKorochkin** [comment]
Also I noticed that after restarting Redis, TS.INFO for the destination key contains NULL in the sourceKey field while should contain the name of the source key.
