### ISSUE TITLE
Crash when loading previous RDB dump when upgrading to `1.4.5`

### ISSUE THREAD

**Issue by dpipemazo** [RedisTimeSeries/RedisTimeSeries#542]
I had previously filed #522 and realize that I was on a non-stable branch, but I do believe backup files were invalidated with the `1.4.5` release.

Our current design on RTS is heavily dependent on our backups being able to continue to be loaded. We're using RTS as a time-series data store and writing to disk frequently. We can tolerate small data gaps between shutdowns and the last known backup file, but it would not be good for us if we had been collecting (and aggregating) data for days or weeks and then had an event where our backup file was invalidated.

Is the backup file going to continue being invalidated at such a high frequency? Will you be planning to offer migration/conversion tools in the event you do need to change the format? Can you perhaps add migration logic to identify a particular issue in a backup file and fix it on load so that we don't get a generic crash?

How do you recommend we proceed if we need persistent RTS data over long periods of time? Is there anything we can/should be doing other than just not upgrading RTS?

**Comment by danni-m** [comment]
@dpipemazo Thanks for the feedback!
You should be able to upgrade/load from 1.2.x without any issues, we did break the rdb during the release process of 1.4 but only for versions that were RC.

We do not plan to break the RDB format between versions at this point.

**Comment by dpipemazo** [comment]
@danni-m thanks for this response -- this is great and much appreciated.
