### ISSUE TITLE
TS.RANGE + AVG + timeBucket 

### ISSUE THREAD

**Issue by racc-costa** [RedisTimeSeries/RedisTimeSeries#560]
Hello team! RedisTimeSeries module has helped us a lot, good work and thanks.

I have a question about how to implement a query using AVG aggregation, I've read the docs and some issues (questions like [489](https://github.com/RedisTimeSeries/RedisTimeSeries/issues/489) here about it, but I don't know if it applies to my use case, so I decided to ask explicitly.

Let's say I have the data below:

```
TS.RANGE ts-1 1603879199000 1603879204000
1) 1) (integer) 1603879199000
   2) 3
2) 1) (integer) 1603879200000
   2) 10
3) 1) (integer) 1603879201000
   2) 20
4) 1) (integer) 1603879202000
   2) 30
5) 1) (integer) 1603879203000
   2) 40
6) 1) (integer) 1603879204000
   2) 8
```

and I need to calculate the average from 1603879200000 to 1603879203000, which is 25 in this case, so I tried:

```
TS.RANGE ts-1 1603879200000 1603879203000 AGGREGATION AVG 3000
1) 1) (integer) 1603879200000
   2) 20
2) 1) (integer) 1603879203000
   2) 40
```

it looks like the 40 was not part of the timeBucket, so I tried:

```
TS.RANGE ts-1 1603879200000 1603879203000 AGGREGATION AVG 3001
1) 1) (integer) 1603879198250
   2) 15
2) 1) (integer) 1603879201251
   2) 35
```
I didn't understand why the first bucket (1603879198250) started before the timestamp (1603879200000).

How should I implement this query to obtain the average of these values?

Thanks!

**Comment by racc-costa** [comment]
I've implemented a `workaround` using a very large AVG timeBucket, as in: 

`TS.RANGE ts-1 1603879200000 1603879203000 AGGREGATION AVG 9223372036854775`

**Comment by gkorland** [comment]
@racc-costa as you found out the workaround is to force a single bucket.

In the first example as you noticed you got two aggregation buckets, which are aligned to 3000 but 1603879203000 is the first timestamp of the next bucket.
```
TS.RANGE ts-1 1603879200000 1603879203000 AGGREGATION AVG 3000
1) 1) (integer) 1603879200000
   2) 20
2) 1) (integer) 1603879203000
   2) 40
```

On your second example the buckets aligned to 3001 
```
TS.RANGE ts-1 1603879200000 1603879203000 AGGREGATION AVG 3001
1) 1) (integer) 1603879198250
   2) 15
2) 1) (integer) 1603879201251
   2) 35
```
The first bucket range is [1603879196500 - 1603879199501) and the second [1603879199501-1603879202502)

**Comment by K-Jo** [comment]
@racc-costa discussing this further here: https://github.com/RedisTimeSeries/RedisTimeSeries/issues/655#issuecomment-831865772 would it be ok to close this?

**Comment by racc-costa** [comment]
> @racc-costa discussing this further here: [#655 (comment)](https://github.com/RedisTimeSeries/RedisTimeSeries/issues/655#issuecomment-831865772) would it be ok to close this?

Yes, sure, thanks @K-Jo .
