### ISSUE TITLE
Duplicate Policy of type Sum

### ISSUE THREAD

**Issue by lpellegr** [RedisTimeSeries/RedisTimeSeries#567]
Is there any plan to add support for a duplicate policy of type SUM in addition to the one mentioned in the docs?

https://oss.redislabs.com/redistimeseries/configuration/#duplicate_policy

This would help when ingesting data from sensors where event occurrence may happen in parallel (i.e. at the same ms) but counted separately (i.e. summed).

**Comment by filipecosta90** [comment]
Hi there @lpellegr the duplicate policy sum has been merged to master and will soon be release as part of v1.4 ( as per #566 ).
In the meantime, you can check the latest docs in:
https://oss.redislabs.com/redistimeseries/master/configuration/#duplicate_policy
and use the current master branch ( or edge docker image to try it out ). 
Please let us know if all is working as you expect :)

**Comment by lpellegr** [comment]
@filipecosta90 What a timing :) I will wait for the PR to be merged and give a try. Thanks for the quick reply.
