### ISSUE TITLE
Bug: ts.createrule allows creating rules with bad aggregation type and crashes for some aggregation types

### ISSUE THREAD

**Issue by yaeltzirulnikov** [RedisTimeSeries/RedisTimeSeries#59]
When running create rule with aggregation type that is a prefix of a valid aggregation type, it works, for example:
ts.createrule key ma 3 dest_key (works since 'ma' is the beginning of 'max')
ts.createrule key av 3 dest_key (works since 'av' is the beginning of 'avg')
ts.createrule key s 3 dest_key (works since 's' is the beginning of 'sum')
This happens because we compare the given aggregation type only according to its length, meaning if receive "ma" we will compare only 2 bytes, and then we'll get that strncmp("ma","max",2) returns equal. The size should be compared according to the expected string.
On the other hand, If we use aggregation type that does not share a prefix with one the valid types, the server crashes.
for example:
ts.createrule key bla 3 dest_key
crash report:
=== REDIS BUG REPORT START: Cut & paste starting from here ===
39274:M 27 Feb 2019 13:21:46.326 # Redis 5.0.0 crashed by signal: 11
39274:M 27 Feb 2019 13:21:46.326 # Crashed running the instruction at: 0x102511b79
39274:M 27 Feb 2019 13:21:46.326 # Accessing address: 0x0
39274:M 27 Feb 2019 13:21:46.326 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
0   redistimeseries.so                  0x0000000102511b79 NewRule + 105

Backtrace:
0   redis-server                        0x000000010235252e logStackTrace + 110
1   redis-server                        0x00000001023528fd sigsegvHandler + 253
2   libsystem_platform.dylib            0x00007fff6e3c0f5a _sigtramp + 26
3   ???                                 0x0000000000000000 0x0 + 0
4   redistimeseries.so                  0x0000000102511a89 SeriesAddRule + 41
5   redistimeseries.so                  0x000000010250f5b0 TSDB_createRule + 560
6   redis-server                        0x0000000102381a33 RedisModuleCommandDispatcher + 147
7   redis-server                        0x000000010230408c call + 220
8   redis-server                        0x0000000102304a54 processCommand + 1556
9   redis-server                        0x000000010231507f processInputBuffer + 495
10  redis-server                        0x00000001022fbe9c aeProcessEvents + 732
11  redis-server                        0x00000001022fc1bb aeMain + 43
12  redis-server                        0x0000000102307cce main + 1726
13  libdyld.dylib                       0x00007fff6e0b2015 start + 1
14  ???                                 0x0000000000000005 0x0 + 5

**Comment by K-Jo** [comment]
@yaeltzirulnikov @danni-m can we validate if this is still valid?

**Comment by gkorland** [comment]
It seems like the server doesn't crash anymore but it does let you aggregate using only the prefix
