### ISSUE TITLE
tests/test_module.py failing to compile due to Python version 3 not supporting trailing 'L

### ISSUE THREAD

**Issue by lavan74** [RedisTimeSeries/RedisTimeSeries#595]
Python version 3.8 does not support a trailing 'L' 
There are hundreds of lines with trailing L and Python version 3.0 does not support this syntax anymore on /RedisTimeSeries/tests/test_module.py

See https://docs.python.org/3/whatsnew/3.0.html#integers for more details

_The repr() of a long integer doesn’t include the trailing L anymore, so code that unconditionally strips that character will chop off the last digit instead. (Use str() instead.)

**Comment by danni-m** [comment]
@lavan74 thanks for opening the issue, we need to convert the code to be python3 compatible.
