### ISSUE TITLE
support TS.DEL

### ISSUE THREAD

**Issue by cwr31** [RedisTimeSeries/RedisTimeSeries#603]
Once a time series is stored, it's occupied memory is monotonically increasing because retention policy will not delete expired data.

TS.DEL key fromTs toTs
means safe delete the 'key' time series's data in fromTs-toTs time interval

**Comment by gkorland** [comment]
Duplicate https://github.com/RedisTimeSeries/RedisTimeSeries/issues/264

**Comment by cwr31** [comment]
> Duplicate #264

Will expired data(use retention policy) be deleted and free memory

**Comment by gkorland** [comment]
data passed the retention time is deleted
