### ISSUE TITLE
TS.ADD not accept 'ON_DUPLICATE` value

### ISSUE THREAD

**Issue by gdadon** [RedisTimeSeries/RedisTimeSeries#604]
steps to reproduce:
1. `TS.ADD test-key 123456 1 ON_DUPLICATE SUM` -> returns 123456 
2. add sample with the same timestamp 
`TS.ADD test-key 123456 1 ON_DUPLICATE SUM`

Expected:
timestamp 123456 sample will be the sum of both inserts
Actual:
(error) TSDB: Timestamp cannot be older than the latest timestamp in the time series

I've try to set the DUPLICATE_POLICY for the key and the module as well and got the same results

**Comment by filipecosta90** [comment]
Hi there @gdadon, please notice that the duplicate policy support was added on version 1.4 as specified [here](https://github.com/RedisTimeSeries/RedisTimeSeries/releases/tag/v1.4.5). 

You can check with docker very easily that you're example works on version >= 1.4:
```
docker run -p 6379:6379 redislabs/redistimeseries:1.4.7
```

Sample commands ( I've included also the `info modules` command output so you can check on your side which version you're using ):

```
$ redis-cli
127.0.0.1:6379> TS.ADD test-key 123456 1 ON_DUPLICATE SUM
(integer) 123456
127.0.0.1:6379> TS.ADD test-key 123456 1 ON_DUPLICATE SUM
(integer) 123456
127.0.0.1:6379> ts.range test-key - + 
1) 1) (integer) 123456
   2) 2
127.0.0.1:6379> info modules
# Modules
module:name=timeseries,ver=10407,api=1,filters=0,usedby=[],using=[],options=[]
```

Can you check your RedisTimeSeries version and close the issue if this solves the above?
Kind regards,

**Comment by gdadon** [comment]
i was on version 10206, closing this

**Comment by filipecosta90** [comment]
> i was on version 10206, closing this

great! PS: you should definitely update to 1.4 to take advantage of all new features =)
