### ISSUE TITLE
Add an offset for aggregation queries to allow for aligned results

### ISSUE THREAD

**Issue by CaptainCuddleCube** [RedisTimeSeries/RedisTimeSeries#607]
Something I've been battling with lately, and it seems like there is no way I can set an offset when I'm aggregating with a timebucket. I'm using the python client.

To illustrate, lets assume I have ingested the data:
```python
In [1]: data
Out[1]:
[('test', 2, 1.585011688970841),
 ('test', 3, 1.5206503063325287),
 ('test', 4, 1.1504853132661446),
 ('test', 5, 1.6335210183200621),
 ('test', 6, 1.9591734441557134),
 ('test', 7, 1.9288271396549201),
 ('test', 8, 1.9699958302004554),
 ('test', 9, 1.205644987739304),
 ('test', 10, 1.7922129321935265),
 ('test', 11, 1.4875839601693452)]
```
This is data that starts at 2, and increase by 1 between values. 

Let's assume I want to get aggregated results from timestamp `5` until `9`, with steps of `3`. 
```python
In [2]: rts.range('test_2', from_time=5, to_time=9, aggregation_type="avg", bucket_size_msec=3)
Out[2]: [(3, 1.63352101832006), 
         (6, 1.95266547133703), 
         (9, 1.2056449877393)]
```

So, you can see that this doesn't start from `5`, but rather, it starts from `3`, and the value in the `3` bucket is the raw value for `5`, the next value is `6`... which makes sense, since it's `3` more than `3`. 

It would make sense to have the system allow for the aggregate to start from `5`, striding through data in steps of 3. 
```python
[(5, 1.84050720071023),
 (8, 1.58782040896988)]
```
In this case, the `5` timestamp will be the average of `5`, `6`, and `7` timestamps, 
and the `8` timestamp will be the average of the `8`, and `9` timestamps.

**Comment by danni-m** [comment]
@CaptainCuddleCube Can you verify if the new `ALIGN` parameter (https://oss.redis.com/redistimeseries/commands/#tsrangetsrevrange) solves your issue?

**Comment by CaptainCuddleCube** [comment]
Hey @danni-m; I didn't know this issue was still open! You can close it! The ALIGN parameter works a treat!
