### ISSUE TITLE
TS.CREATE and key exist error

### ISSUE THREAD

**Issue by miohtama** [RedisTimeSeries/RedisTimeSeries#634]
Currently command documentation does not cover the situation what happens if you try to re-create an existing key.

You get `TSDB: key already exists`.

Happy to add this to manual if there are no special cases that should be taken to account.

**Comment by danni-m** [comment]
@miohtama we will definitely appreciate any help in docs to clarify this.

**Comment by filipecosta90** [comment]
closing this one given #636 fixed it.
