### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ricrug** [RedisTimeSeries/RedisTimeSeries#647]
**Steps to reproduce:**
```bash
git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git
cd RedisTimeSeries
make setup
```

**Expected behavior:**
_Build ends successfully_

**Actual behavior:**
```bash
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:184: ../bin/linux-x64-release/redistimeseries.so] Error 1
make: *** [Makefile:52: run] Error 2
```

**Comment by gkorland** [comment]
Which Linux distribution are you using?

**Comment by ricrug** [comment]
> Which Linux distribution are you using?

Fedora 33

**Comment by gkorland** [comment]
I just ran the build on fedora 33, can you please post more of the log?

**Comment by gkorland** [comment]
OK, I think I found the issue, can you please try to upgrade `/deps/RedisModulesSDK` to master?
Just call:

```
cd ./deps/RedisModulesSDK
git checkout master
cd ../../
make build
```

**Comment by ricrug** [comment]
It works, thank you!
