### ISSUE TITLE
aggregation + timebuckets, timestamps not bucket aligned

### ISSUE THREAD

**Issue by grantthomas** [RedisTimeSeries/RedisTimeSeries#655]
In issue #560  @gkorland pointed out the workaround for using a non timebucket aligned timebucket is to use a sufficiently large timebucket that the desired data is contained within one bucket.

example
`ts.range series 13000 18000 AGGREGATION AVG 9223372036854775`

This effectively provides a huge bucket and filters 5000 ms worth of data into it.
if a timebucket of 5000 was used directly, buckets 10000-15000 and 15000-20000 would be returned

Are there any plans to allow for a non timebucket aligned timebucket?

for example, every second I need to know the running average for the last 5 seconds.

I would rather be able to say something like 
`ts.revrange series - + AGGREGATION 5000 count 1`

instead of
`rs.revrange series <calculated now - 5000> + AGGREGATION 9223372036854775`

or
`rs.revrange series - + count 5`
and then manually calculate the average.

**Comment by K-Jo** [comment]
We discussed this internally and are currently agreeing upon the following syntax

```TS.MRANGE / TS.RANGE .... [AGGREGATION aggregationType timeBucket [ALIGN alignOption]] ...```

alignOption can be:
- `start` or `-`
- `end` or  `+`
- a timestamp in milliseconds: RTS will calculate an offset: `timestamp % timeBucket` 

@grantthomas @danni-m @filipecosta90

**Comment by grantthomas** [comment]
> We discussed this internally and are currently agreeing upon the following syntax
> 
> `TS.MRANGE / TS.RANGE .... [AGGREGATION aggregationType timeBucket [ALIGN alignOption]] ...`
> 
> alignOption can be:
> 
> * `start` or `-` (a synonym for start)
> * `end` or  `+` (a synonym for end)
> * a timestamp in milliseconds: RTS will calculate an offset: `timestamp % timeBucket`
> 
> @grantthomas @danni-m @filipecosta90

@K-Jo, sounds great.

To be clear, are the align start/end options referenced to the key's overall first/last, or is this aligned to the queried range?
Also, can you elaborate on the behavior on 'ALIGN <timestamp>'?

example: 
`ts.range key 13000 18000 AGGREGATION AVG 5000 ALIGN start`

Would the alignment be on the timestamp 0, or 13000 ?

**Comment by danni-m** [comment]
@grantthomas sorry for the late response, in this case the alignment will be on 13000
