### ISSUE TITLE
Building from source uninstalls `redis-py` version and pegs it to `2.10.5`

### ISSUE THREAD

**Issue by dpipemazo** [RedisTimeSeries/RedisTimeSeries#661]
An unintended side effect of building this package from source is that the tests seem to peg `redis-py` to `2.10.5`. It would be nice to make/run the tests in a virtual environment or similar so as to not peg the host's `redis-py` version to something so out-of-date.

https://github.com/RedisTimeSeries/RedisTimeSeries/blob/master/tests/flow/Pipfile.lock

**Comment by chayim** [comment]
Looks like we've locked the dependencies, and pinned it in the Pipfile. I'll validate in an Ubuntu 18.04 docker that the latest redis-py release doesn't break anything (to start).

**Comment by dpipemazo** [comment]
Thanks for the quick response! We've been running on redis-py `3.5.3` for 6 months or so now and have seen no issues if that helps.
