### ISSUE TITLE
TS.RANGE on downsampled key returning incorrect results

### ISSUE THREAD

**Issue by nunofgs** [RedisTimeSeries/RedisTimeSeries#699]
Hi, I'm attempting to use TS.RANGE to retrieve an aggregated average over one week of values. The following is with version 1.4.8:

![Screenshot 2021-04-27 at 14 05 44](https://user-images.githubusercontent.com/92085/116246402-e0326f00-a761-11eb-82b2-040ab35600b8.png)

As you can see, the TS.RANGE over the rule `temperature:ONE_WEEK` returns incorrect results, whereas calling TS.RANGE on the base key `temperature`, seems to work just fine.

Is this a bug?

**Comment by danni-m** [comment]
@nunofgs What do you mean by `incorrect`?

The only difference I see is the last sample which doesn't exists on the aggregated key because the aggregation bucket was not closed yet, so we do push the aggregation to the downstream key,

**Comment by nunofgs** [comment]
Hi @danni-m. Yes, that's pretty much what I meant, except I didn't know that that was the reason for the differing results.

It seems like this is a design choice but, in my use case at least, it is unwanted. That last value (with timestamp `1619355370046`) has been inserted and the timestamp has elapsed, so in our use case, it should show up in a query.

Is there any way to alter this behavior? otherwise my only choice would be to not use downsampling rules :(

**Comment by danni-m** [comment]
@nunofgs If you want you can always query the downsampled key and run a query on the original key to have up2date data.

Updating the downsampled key each insert will slow down `TS.ADD` command which we want to avoid.

There are 2 options here:
1. Add an option to Rules to update on every insert
2. bridge the gap by querying the upstream key when the downsampled key is queried.

the first one is probably safer while the 2nd one might create issues when querying multiple keys.

**Comment by nunofgs** [comment]
Thanks @danni-m, that's very helpful. I agree that option 1) is not desirable. I would also prefer not to hurt the insertion performance.

Would it make sense, as a third option, to add a parameter to ts.range that does that automatically? (grabs the missing data from the upstream key)

**Comment by danni-m** [comment]
@nunofgs yes, thats adds a complications in the future if we want to propagate it to MRANGE/GET/MGET. Currently we have a single notion of whats inside a key, by reading from the upstream key it means that there's more data in a different key which we will need to read and expand the query from one key to another. Also, it will have to apply to all downsampled keys in the same query.

**Comment by nunofgs** [comment]
Understood, we'll gapfill on the client side if needed. Closing for now, to keep things tidy. Thanks @danni-m
