### ISSUE TITLE
Filter by list

### ISSUE THREAD

**Issue by K-Jo** [RedisTimeSeries/RedisTimeSeries#73]
Filter that allows to query timeseries with a field that can has one of the values in the supplied list.
```
TS.MRANGE - + AGGREGATION max 600000000000 FILTER hostname=host_0 field=(metric1,metric2,...,metric5)
```

**Comment by gkorland** [comment]
We might need to think the filter API and see if we need to define something more generic

**Comment by gkorland** [comment]
Or we should keep this one simple and use another keyword/command for more general filter based on RediSearch
