### ISSUE TITLE
Clarification on handling multiple samples for the same specific time

### ISSUE THREAD

**Issue by pushshift** [RedisTimeSeries/RedisTimeSeries#737]
Let's say I have two temperature probes that send data for the exact same time. The first probe has a label key value of "location downstairs" and the second probe has the label "location upstairs."

Can you have two data points for the same exact time (but with different labels) or should you create a timeseries for each probe? I guess what I'm asking is if the unique key is the time itself or a combination of time and labels?

Thanks!

**Comment by filipecosta90** [comment]
Hi there @pushshift, you should create a timeseries for each probe. Please notice that you will still be able to do multi-series queries, etc... ( check for example the TS.MRANGE [docs](https://oss.redislabs.com/redistimeseries/master/commands/#tsmrangetsmrevrange) ). 
I can give you an example based on your probes info. 

**Let's use docker and redistimeseries:edge container:**
```
docker run -p 6379:6379 redislabs/redistimeseries:edge
```

**Then create, populate and query:**

Consider the same timestamp as 1000.

```bash
$ redis-cli 
127.0.0.1:6379> ts.create probe1 LABELS location downstairs type probe
OK
127.0.0.1:6379> ts.create probe2 LABELS location upstairs type probe
OK
127.0.0.1:6379> ts.add probe1 1000 10.0
(integer) 1000
127.0.0.1:6379> ts.add probe2 1000 15.0
(integer) 1000
127.0.0.1:6379> ts.mrange - + WITHLABELS FILTER type=probe 
1) 1) "probe1"
   2) 1) 1) "location"
         2) "downstairs"
      2) 1) "type"
         2) "probe"
   3) 1) 1) (integer) 1000
         2) 10
2) 1) "probe2"
   2) 1) 1) "location"
         2) "upstairs"
      2) 1) "type"
         2) "probe"
   3) 1) 1) (integer) 1000
         2) 15
```

Hope the above snippet helped. 
Feel free to either ask further info or close the issue if you have all info required. Kind regards :)

**Comment by pushshift** [comment]
Thanks for the detailed answer! I was hesitant to add this question as an issue but this should be very helpful for others as well.

Appreciate the clarification!
