### ISSUE TITLE
TS.MGET Get latest value of several timeseries

### ISSUE THREAD

**Issue by K-Jo** [RedisTimeSeries/RedisTimeSeries#74]
Similar as TS.GET but with filters in stead of a single key
```
TS.MGET FILTER filter..
```

**Comment by gkorland** [comment]
I don't think we need TS.GET or TS.MGET.
It feels like TS.RANGE and TS.MRANGE cover these two

**Comment by gkorland** [comment]
We should also add a way to block on TS.GET/TS.RANGE for result and I think we should add support to get the last count results or the last X seconds

**Comment by K-Jo** [comment]
or the last x samples

**Comment by K-Jo** [comment]
https://github.com/RedisLabsModules/RedisTimeSeries/pull/92

**Comment by K-Jo** [comment]
Needs documentation, thanks @itamarhaber
