### ISSUE TITLE
TS.DEL should update down sampling 

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/RedisTimeSeries#744]
1. When an event is deleted the relevant downsample should be updated
2. When an event is deleted and a retention policy is set on the source the delete should return an error in case part of this bucket was already expired (can't recalculate the downsample effect)

**Comment by filipecosta90** [comment]
@gkorland @OfirMos isn't this solved on v1.6 already?

**Comment by OfirMos** [comment]
@filipecosta90 Yes it have been pushed, @gkorland Can I just close it? Should I add the commit_id here?
