### ISSUE TITLE
TS.MRANGE not returning all entries with the expected label

### ISSUE THREAD

**Issue by atwoz** [RedisTimeSeries/RedisTimeSeries#798]
Using version 1.4.9. It was previously working fine with version 1.2.7. This started to happen just as I updated.

I should get data in the 4443.pres key but it is returning empty.
```
127.0.0.1:6379> ts.mrange 1625596680000 1625897690000 FILTER did=4443
1) 1) "4443.acstate"
   2) (empty array)
   3) 1) 1) (integer) 1625626860000
         2) 2102278
      2) 1) (integer) 1625672040000
         2) 14685198
      3) 1) (integer) 1625672100000
         2) 14685198
2) 1) "4443.humi"
   2) (empty array)
   3) (empty array)
3) 1) "4443.humi_avg_10min_1mon"
   2) (empty array)
   3) (empty array)
4) 1) "4443.occupancy"
   2) (empty array)
   3) (empty array)
5) 1) "4443.pres"
   2) (empty array)
   3) (empty array)
6) 1) "4443.temp"
   2) (empty array)
   3) (empty array)
7) 1) "4443.temp_avg_10min_1mon"
   2) (empty array)
   3) (empty array)
8) 1) "4443.win"
   2) (empty array)
   3) (empty array)
```

Here is the ts.info of the 4443.pres key
```
127.0.0.1:6379> ts.info 4443.pres
 1) totalSamples
 2) (integer) 91745
 3) memoryUsage
 4) (integer) 33449
 5) firstTimestamp
 6) (integer) 1619819400000
 7) lastTimestamp
 8) (integer) 1626807360000
 9) retentionTime
10) (integer) 8553600000
11) chunkCount
12) (integer) 8
13) chunkSize
14) (integer) 4096
15) chunkType
16) compressed
17) duplicatePolicy
18) (nil)
19) labels
20) 1) 1) "did"
       2) "4443"
21) sourceKey
22) (nil)
23) rules
24) (empty array)
```

Did something change? I cannot seem to find what I am doing wrong or if it is some kind of breaking change or bug.

Regards.

**Comment by filipecosta90** [comment]
@atwoz thank you for reporting it. Is it possible to provide an rdb with the data so we can replicate on our side and understand where is the issue?

**Comment by atwoz** [comment]
@filipecosta90 Hi Felipe. Sure, I can share the rdb with you, is there any way for me to send it to you without posting it here?

Thanks.

**Comment by filipecosta90** [comment]
> @filipecosta90 Hi Felipe. Sure, I can share the rdb with you, is there any way for me to send it to you without posting it here?
> 
> Thanks.

sure :) either to filipe@redislabs.com or filipecosta.90@gmail.com

**Comment by atwoz** [comment]
Hi, I sent the email with the rdb file. I hope you can replicate the issue. Regards.

**Comment by filipecosta90** [comment]
@atwoz should be able to look at it still today. will keep you posted :)

**Comment by filipecosta90** [comment]
@atwoz closing it after our email exchange update and check all is working as expected.
