### ISSUE TITLE
Document FILTER_BY_TIME/VALUE

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/RedisTimeSeries#805]
ref https://github.com/RedisTimeSeries/RedisTimeSeries/pull/722

**Comment by filipecosta90** [comment]
@gkorland even tough this is already documented in https://oss.redislabs.com/redistimeseries/master/commands/#tsmrangetsmrevrange
as seen in:
![image](https://user-images.githubusercontent.com/5832149/126970634-98a28642-228d-4f4c-8435-a041cfc78fd2.png)

We can take this issue to add an example about it
