### ISSUE TITLE
Add support for more aggregation functions (MEDIAN, DEVIATION) 

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/RedisTimeSeries#84]

**Comment by ashtul** [comment]
standard deviation is added in [PR #125](https://github.com/RedisTimeSeries/RedisTimeSeries/pull/125).

**Comment by ashtul** [comment]
Suggest to change design of aggregation insertion from overwriting itself until next bucket start to writing only when bucket ends.

**Comment by ashtul** [comment]
Resolved in #143
