### ISSUE TITLE
MGET Redis Cluster

### ISSUE THREAD

**Issue by Strafo** [RedisTimeSeries/RedisTimeSeries#854]
Hello,
Let's say I create the following timeseries with these commands:

1. TS.ADD temperature:{sensor1}   *  26 LABELS sensor_id=1
2. TS.ADD umidity:{sensor1}   *  64  LABELS sensor_id=1 

I use the hashtag because redis is in cluster mode and I want all the measurements related to a sensor to be on the same node, so that I can perform a mrange.

If I use a client library like redis++, it automatically handles MOVED responses for me. (without knowing which node I am connecting to)

The problem is that mrange if performed on a node that does not contain the data, returns me (empty array) instead of MOVED; then the library believes that the command was successful and does not continue ....

So I wonder if a different approach (instead of empty array) is possible or if it is right as it is

**Comment by danni-m** [comment]
Hi @Strafo,
You have 2 options:
1. You will need to access the specific node (you can find it by calling TS.GET for example) and pin the connection (im not sure if redis++ supports that), or you can ask for a connection to a specific hash slot (again not sure if redis++ supports that).
2. On 1.6-rc1 and master you can load RedisGears alongside which will make `MGET`, `MRANGE`, and `QUERYINDEX` cluster-aware and will handle the forwarding internally by the cluster.

**Comment by Strafo** [comment]
thx
