### ISSUE TITLE
Update documentation to reflect that `TS.ALTER` can set `DUPLICATE_POLICY`

### ISSUE THREAD

**Issue by dpipemazo** [RedisTimeSeries/RedisTimeSeries#888]
It seems that `TS.ALTER` can set `DUPLICATE_POLICY` as of 1.4.13, which is a very nice feature! It would be nice to have this reflected in the [docs](https://oss.redis.com/redistimeseries/commands/#tsalter).

This was confirmed through running `TS.ALTER` and then `TS.INFO` on a key

**Comment by nerg4l** [comment]
@OfirMos I think this can be closed since  #1076 was merged.

**Comment by LiorKogan** [comment]
Updated. See https://redis.io/commands/ts.alter/
