### ISSUE TITLE
Update documentation to reflect that `TS.ADD` can set `DUPLICATE_POLICY`

### ISSUE THREAD

**Issue by dpipemazo** [RedisTimeSeries/RedisTimeSeries#889]
`TS.ADD` seems to support setting a `DUPLICATE_POLICY` if the add implicitly creates a stream which is quite nice. This behavior seems to be explicitly different from the `ON_DUPLICATE` argument which explicitly overrides the key's set `DUPLICATE_POLICY` if passed. It would be nice for the [docs](https://oss.redis.com/redistimeseries/commands/#tsadd) to reflect this.

**Comment by danni-m** [comment]
The docs are update with the `ON_DUPLICATE` parameter.
