### ISSUE TITLE
Redis Gears dependency?

### ISSUE THREAD

**Issue by martinberoiz** [RedisTimeSeries/RedisTimeSeries#903]
Hello,

I compiled `redistimeseries.so` and I am trying to load the module now.

The `redis-server` doesn't like the installation. It appears to be that it also needs the Redis gears module.

    31292:M 22 Nov 2021 13:42:24.425 # Module /home/myusername/RedisTimeSeries/bin/redistimeseries.so failed to load: /home/myusername/RedisTimeSeries/bin/redistimeseries.so: cannot open shared object file: Permission denied
    31292:M 22 Nov 2021 13:49:58.348 * <timeseries> RedisTimeSeries version 999999, git_sha=98bb2ca340cb38ae077970545e2a5c840a8a6aa9
    31292:M 22 Nov 2021 13:49:58.348 * <timeseries> Redis version found by RedisTimeSeries : 5.0.14 - oss
    31292:M 22 Nov 2021 13:49:58.348 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
    31292:M 22 Nov 2021 13:49:58.348 * <timeseries> loaded server DUPLICATE_POLICY: block
    31292:M 22 Nov 2021 13:49:58.348 * <timeseries> Setting default series ENCODING to: compressed
    31292:M 22 Nov 2021 13:49:58.348 # <timeseries> could not initialize RedisGears_GetCompiledOs

    31292:M 22 Nov 2021 13:49:58.348 # <timeseries> Failed initialize RedisGears API

Do I need to install Redis Gears too? Is it a dependency?

**Comment by gkorland** [comment]
@martinberoiz I see that you're using an unofficial version straight from the code, please try to pull a newer version of the code and rebuild the module this external dependency was removed.

**Comment by danni-m** [comment]
@martinberoiz this is how it looks on master currently:
```
45442:M 23 Nov 2021 10:11:49.222 # Server initialized
45442:M 23 Nov 2021 10:11:49.434 * <timeseries> RedisTimeSeries version 999999, git_sha=d1e29a12962249fb2fbef05aeba421cb81434331
45442:M 23 Nov 2021 10:11:49.434 * <timeseries> Redis version found by RedisTimeSeries : 255.255.255 - oss
45442:M 23 Nov 2021 10:11:49.434 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
45442:M 23 Nov 2021 10:11:49.434 * <timeseries> loaded server DUPLICATE_POLICY: block
45442:M 23 Nov 2021 10:11:49.434 * <timeseries> Setting default series ENCODING to: compressed
45442:M 23 Nov 2021 10:11:49.434 * <timeseries> Detected redis oss
45442:M 23 Nov 2021 10:11:49.435 * Module 'timeseries' loaded from /Users/*/code/RedisTimeSeries/bin/macos-arm64-release/redistimeseries.so
45442:M 23 Nov 2021 10:11:49.435 * Ready to accept connections
```

**Comment by martinberoiz** [comment]
Thank you for replying. I re-downloaded the module and this happened now:

    $ sudo make setup
    Setting up system...
    apt-get -qq update -y
    # readies version: fb5c5b1
    /usr/bin/python3 -m pip install --disable-pip-version-check wheel
    /usr/bin/python3 -m pip install --disable-pip-version-check setuptools --upgrade
    apt-get -qq install -y git jq curl
    /home/martin/RedisTimeSeries/deps/readies/bin/enable-utf8
    apt-get -qq install -y autoconf libtool m4 automake
    apt-get -qq install -y openssl
    /home/martin/RedisTimeSeries/deps/readies/bin/getgcc --modern
    apt-get -qq update -y
    # readies version: fb5c5b1
    cannot install modern gcc for buster
    command failed: { /home/martin/RedisTimeSeries/deps/readies/bin/getgcc --modern; } >/tmp/tmpjewojkw8 2>&1
    make: *** [Makefile:25: setup] Error 1

It's strange because I do have gcc installed:

    $ gcc --version
    gcc (Debian 11.2.0-10) 11.2.0
    Copyright (C) 2021 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Installing the other way:

    ./deps/readies/bin/getpy3
    ./system-setup.py

gives the same error. Can you help me with this?

**Comment by danni-m** [comment]
@martinberoiz can you try again? we move from RedisGears to LibMR and improved the build system.

**Comment by martinberoiz** [comment]
works like a charm now, thank you!

**Comment by mcauto** [comment]
same here.

I use https://github.com/Grokzen/docker-redis-cluster/blob/master/Dockerfile.

I append install script below in Dockerfile.

```Dockerfile
...
# install redis timeseries
RUN git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git && \
    cd RedisTimeSeries && \
    make setup build && \
    mv bin/redistimeseries.so /bin/redistimeseries.so
```

then occur errors.

```bash
#20 35.01 cannot install modern gcc for buster
#20 35.01 command failed: /data/RedisTimeSeries/deps/readies/bin/getgcc --modern
#20 35.02 
#20 35.02 In /data/RedisTimeSeries/sbin/setup:
#20 35.02 7        . $READIES/shibumi/defs
#20 35.02 8        
#20 35.02 9        $READIES/bin/getpy3
#20 35.02 10   >>> $ROOT/sbin/system-setup.py $SETUP_ARGS
#20 35.02 
#20 35.02 make: *** [Makefile:34: setup] Error 1
```
