### ISSUE TITLE
Deploy RedisTimeSeries on EKS

### ISSUE THREAD

**Issue by vikram-yerneni** [RedisTimeSeries/RedisTimeSeries#909]
Fellas,
Has anyone set this RedisTimeSeries on EKS? Are there a helm charts to set it up?
Please and thank you.

Thanks
Vikram

**Comment by chayim** [comment]
Unfortunately, we don't currently have any helm charts in place - though this is one of my dreams.  But - if you have charts in place to run **redis** then you could use the published docker image [redislabs/redistimeseries](https://hub.docker.com/r/redislabs/redistimeseries/).  You get a redis, with timeseries pre loaded. _1.4.13_ is the latest release, and if you'd like the most up-to-date master image you can grab the _edge_ tag.

**Comment by danni-m** [comment]
@vikram-yerneni You can also try to use [Redis Enterprise on K8s](https://docs.redis.com/latest/kubernetes/)

**Comment by vikram-yerneni** [comment]
Thanks fellas for the inputs.

**Comment by vikram-yerneni** [comment]
> Unfortunately, we don't currently have any helm charts in place - though this is one of my dreams. But - if you have charts in place to run **redis** then you could use the published docker image [redislabs/redistimeseries](https://hub.docker.com/r/redislabs/redistimeseries/). You get a redis, with timeseries pre loaded. _1.4.13_ is the latest release, and if you'd like the most up-to-date master image you can grab the _edge_ tag.

I started working on to use Bitnami charts.. Hopefully, this will allow me t modify the Bitnami's charts to pull in this docker repo.

**Comment by vikram-yerneni** [comment]
The setup @chayim mentioned worked with one exception. Its not loading modules, however there is a workaround for the same: https://github.com/RedisTimeSeries/RedisTimeSeries/issues/910#issuecomment-981086825
