### ISSUE TITLE
the module was not loaded by the docker

### ISSUE THREAD

**Issue by baikeh** [RedisTimeSeries/RedisTimeSeries#910]
![Screen Shot 2021-11-26 at 20 57 34](https://user-images.githubusercontent.com/32256469/143584570-099e05fc-636e-41a3-841d-7c582649eab2.png)
I am using the `redislabs/redistimeseries:edge` image to run it in docker, but I found the the redis sever does not load the TImeSeries module (the `MODULE LIST` command is the empty).

I also attached into the docker, and found the `redistimeseries.so` is under the directory: `/usr/lib/redis/modules`, everything looks fine. So what the problem and how to solve this? 

thanks a lot for any help.

**Comment by gkorland** [comment]
Can you please share more details? where did you run the docker? Please share the console out put when starting the docker

**Comment by baikeh** [comment]
> Can you please share more details? where did you run the docker? Please share the console out put when starting the docker

This is the command running in my centos7 server:

> sudo docker run --restart=always --name rts -p 6379:6379 -d redislabs/redistimeseries:edge --requirepass "123456"

And the output is below:
![1](https://user-images.githubusercontent.com/32256469/143679712-5dffabbb-9068-4f93-a324-01b043cf7c18.png)

**Comment by baikeh** [comment]
@gkorland  just let u know, after more investigation, I used the `module load` command to load the module manually, it is works for me, this is the workaround .
![1](https://user-images.githubusercontent.com/32256469/143770106-40cfd63d-cbf0-48a7-b02d-faa855fe0271.png)

**Comment by gkorland** [comment]
It seems like the ` --requirepass "123456"` broke it.

You can run it like that:

```
sudo docker run --restart=always --name rts --rm -p 6379:6379 -d redislabs/redistimeseries:edge --requirepass "123456" --loadmodule /usr/lib/redis/modules/redistimeseries.so
```

**Comment by baikeh** [comment]
@gkorland  it works, thanks for your help.
