### ISSUE TITLE
FILTER_BY_TS has no effect?

### ISSUE THREAD

**Issue by 98christianp** [RedisTimeSeries/RedisTimeSeries#926]
Hi I'm experimenting with FILTER_BY_TS on TS.MRANGE call

Given a timeseries with timestamp 100, 200

`TS.MRANGE - + FILTER_BY_TS 100 FILTER filter=value`

Expected return array:

```
1) 1) "ts"
   2) (empty array)
   3) 1) 1) (integer) 100
         2) 10
```
         
Actual return array:

```
1) 1) "ts"
   2) (empty array)
   3) 1) 1) (integer) 100
         2) 10
      2) 1) (integer) 200
         2) 20

```

Running the query like this however produces the expected result

`TS.MRANGE 100 100  FILTER filter=value`

**Comment by filipecosta90** [comment]
Hi there @98christianp I suspected you're using a redistimeseries version < v1.6 ( this feature was introduce on v1.6 ). 
You can check your redistimeseries version by issuing the `INFO MODULES` command.

Here's a working sample with docker and version 1.6.0:
```
$ docker run -d -p 6379:6379 redislabs/redistimeseries:1.6.0
694a3bec970c12a569d501b32500bfcbb4eab69ac93a88196d030e54a9665ae9

fco@fco-ThinkPad-T490:~/redislabs/testing-infrastructure/terraform$ redis-cli
127.0.0.1:6379> info modules
# Modules
module:name=timeseries,ver=10600,api=1,filters=0,usedby=[],using=[],options=[]
127.0.0.1:6379> ts.create t1 LABELS label value
OK
127.0.0.1:6379> ts.add t1 100 50.0
(integer) 100
127.0.0.1:6379> ts.add t1 200 150.0
(integer) 200
127.0.0.1:6379> TS.MRANGE - + FILTER label=value
1) 1) "t1"
   2) (empty array)
   3) 1) 1) (integer) 100
         2) 50
      2) 1) (integer) 200
         2) 150
127.0.0.1:6379> TS.MRANGE - + FILTER_BY_TS 100 FILTER label=value
1) 1) "t1"
   2) (empty array)
   3) 1) 1) (integer) 100
         2) 50
127.0.0.1:6379> 
```

Can you check your TS version and the above example also?

**Comment by 98christianp** [comment]
Thanks for the response, the example does indeed run no problem, do you have any plans on when the GA for 1.6.0 will be released, seems like azure isn't ready to adopt this version yet

**Comment by K-Jo** [comment]
@98christianp yes you're right, we have some issue with our docs system that it's not clear you're looking at docs of non GA code. Agreed. /cc @gkorland 

We're hoping to reach GA quality early in the next calendar year.
