### ISSUE TITLE
Run helm command with attached 'module load' command

### ISSUE THREAD

**Issue by vikram-yerneni** [RedisTimeSeries/RedisTimeSeries#935]
Fellas,
Since we don't have helm setup for redistimeseries, I modified Redis helm charts to deploy redistimeseries (https://github.com/RedisTimeSeries/RedisTimeSeries/issues/909). It worked with one caveat, the module is not loading. So I had to login to Redis-cli and load the module manually.
Is there a way to add the load module either to the helm chart or in the Redis values.yaml file so that the module will be loaded by default?
Redis charts: https://github.com/bitnami/charts/tree/master/bitnami/redis

Thanks
Vikram

**Comment by danni-m** [comment]
@vikram-yerneni im not an expert in Helm, but it looks like `master.configuration` might be the place you are looking for.
Try to pass there the load-module command, for example: `--loadmodule /path/to/redistimeseries.so`

**Comment by vikram-yerneni** [comment]
Thanks @danni-m , somehow the master configuration file is not accepting the additional configuration setup.
`master:
  ## @param master.configuration Configuration for Redis&trade; master nodes
  ## ref: https://redis.io/topics/config
  ##
  configuration: "MODULE load /usr/lib/redis/modules/redistimeseries.so"`

The pod is failing with error: 
`redis *** FATAL CONFIG FILE ERROR (Redis 6.0.9) ***                                                                          │
│ redis Reading the configuration file, at line 3                                                                              │
│ redis >>> 'MODULE load /usr/lib/redis/modules/redistimeseries.so'                                                            │
│ redis Bad directive or wrong number of arguments        `

**Comment by vikram-yerneni** [comment]
Sorry, it worked
`master:
   @param master.configuration Configuration for Redis&trade; master nodes
   ref: https://redis.io/topics/config
  configuration: "loadmodule /usr/lib/redis/modules/redistimeseries.so"`

Thanks @danni-m
