### ISSUE TITLE
aggregation, time-buckets, and align

### ISSUE THREAD

**Issue by vgoklani** [RedisTimeSeries/RedisTimeSeries#943]
Hello, thank you for releasing this module.

I need to resample our data into 1min time-buckets, where the data in each bucket is summed, and the alignment is to the right. Using pandas (in python), this would be equivalent to

    [dataframe].resample("1min", label="right").sum()

More specifically, an event that has a raw timestamp of 11:12:01s will be counted towards 11:13. This would match the behavior from pandas.

I tried to implement this as follows:

    .range(key=..., from_time=0, to_time="+", aggregation_type='sum', bucket_size_msec=60000, align='end')

Unfortunately the timestamps are not being shifted to the next minute. Am I doing this correctly, or is there another approach?

Thanks!

**Comment by danni-m** [comment]
@vgoklani which RedisTimeSeries version are you using? can you run it on the server with redis-cli and paste here the output?

**Comment by gkorland** [comment]
@vgoklani which client do you use and what version?

**Comment by vgoklani** [comment]
Hello,

@danni-m [{b'name': b'timeseries', b'ver': 10410}]

'redis_version': '6.0.9'

running via docker: redislabs/redistimeseries:latest

@gkorland 

I'm using the latest version of redis-python

thanks!

**Comment by danni-m** [comment]
@vgoklani The timestamp aligment is supported only on 1.6+ or master versions.

**Comment by vgoklani** [comment]
thanks @danni-m - is that available via docker?

**Comment by vgoklani** [comment]
Hello @danni-m  and @gkorland 

I've pulled the docker image from here:

    redislabs/redistimeseries:1.6.1

and created some explicit test code using python-redis but with raw commands:

	r.execute_command("MODULE LIST")

	=> [{b'name': b'timeseries', b'ver': 10413}]

	# dummy data created in python
	t1 = int(1000 * datetime.datetime(2021, 12, 16, 10, 1, 0).timestamp()) # Dec 16, 2021 # 10:01:00
	t2 = int(1000 * datetime.datetime(2021, 12, 16, 10, 1, 1).timestamp()) # Dec 16, 2021 # 10:01:01
	t3 = int(1000 * datetime.datetime(2021, 12, 16, 10, 1, 2).timestamp()) # Dec 16, 2021 # 10:01:02

	key = 'test'
	s1 = f'TS.ADD {key} {t1} 123 RETENTION 0 ON_DUPLICATE SUM'
	s2 = f'TS.ADD {key} {t2} 456 RETENTION 0 ON_DUPLICATE SUM'
	s3 = f'TS.ADD {key} {t3} 789 RETENTION 0 ON_DUPLICATE SUM'

	rts = r.ts()
	rts.execute_command(s1)
	rts.execute_command(s2)
	rts.execute_command(s3)

	rts.execute_command(f'TS.RANGE {key} 0 +')
	[[1639666860000, b'123'], [1639666861000, b'456'], [1639666862000, b'789']]

	rts.execute_command(f'TS.RANGE {key} 0 + AGGREGATION sum 60000')
	[[1639666860000, b'1368']]

	rts.execute_command(f'TS.RANGE {key} 0 + AGGREGATION sum 60000 ALIGN end')
	[[1639666860000, b'1368']]

**Comment by gkorland** [comment]
Can you please try with the edge tag?


redislabs/redistimeseries:edge

**Comment by vgoklani** [comment]
thank you @gkorland 

I just tried the edge version, and now the ALIGN command does indeed change the result.

However, it looks like the alignment is being done based on the "end" time value.

Unfortunately we do need to replicate the pandas results, but it's not clear to me how to choose the end value. We also don't want to have to think about this, as the pandas command .resample("1min", label="right").sum() just works automatically

	r.delete('test')
	r.execute_command("MODULE LIST")

	[{b'name': b'timeseries', b'ver': 999999}]

	t0 = int(1000 * datetime.datetime(2021, 12, 16, 9, 59, 0).timestamp()) # Dec 16, 2021 # 9:59:00
	t1 = int(1000 * datetime.datetime(2021, 12, 16, 10, 1, 0).timestamp()) # Dec 16, 2021 # 10:01:00
	t2 = int(1000 * datetime.datetime(2021, 12, 16, 10, 1, 1).timestamp()) # Dec 16, 2021 # 10:01:01
	t3 = int(1000 * datetime.datetime(2021, 12, 16, 10, 1, 2).timestamp()) # Dec 16, 2021 # 10:01:02

	key = 'test'
	s0 = f'TS.ADD {key} {t0} 42 RETENTION 0 ON_DUPLICATE SUM'
	s1 = f'TS.ADD {key} {t1} 123 RETENTION 0 ON_DUPLICATE SUM'
	s2 = f'TS.ADD {key} {t2} 456 RETENTION 0 ON_DUPLICATE SUM'
	s3 = f'TS.ADD {key} {t3} 789 RETENTION 0 ON_DUPLICATE SUM'

	rts = r.ts()
	rts.execute_command(s0)
	rts.execute_command(s1)
	rts.execute_command(s2)
	rts.execute_command(s3)

	rts.execute_command(f'TS.RANGE {key} 0 +')

	[[1639666740000, b'42'],
	 [1639666860000, b'123'],
	 [1639666861000, b'456'],
	 [1639666862000, b'789']]

	rts.execute_command(f'TS.RANGE {key} 0 + AGGREGATION sum 60000')

	[[1639666740000, b'42'], [1639666860000, b'1368']]

	w = rts.execute_command(f'TS.RANGE {key} 0 + AGGREGATION sum 60000 ALIGN 1639667400000')

	[[1639666740000, b'42'], [1639666860000, b'1368']]

	pd.to_datetime(w[0][0], unit='ms'), pd.to_datetime(w[1][0], unit='ms')

	(Timestamp('2021-12-16 14:59:00'), Timestamp('2021-12-16 15:01:00'))

For this example, the answers we want would be 15:00 and 15:02 respectively, which is what Pandas gives us.

Is there a way to make this work? Thanks!

**Comment by gkorland** [comment]
This is how ALIGN works:

* ALIGN - Time bucket alignment control for AGGREGATION. This will control the time bucket timestamps by changing the reference timestamp on which a bucket is defined.
     Possible values:
     * `start` or `-`: The reference timestamp will be the query start interval time (`fromTimestamp`).
     * `end` or `+`: The reference timestamp will be the query end interval time (`toTimestamp`).
     * A specific timestamp: align the reference timestamp to a specific time.
     * **Note:** when not provided alignment is set to `0`.

**Comment by vgoklani** [comment]
Hi @gkorland @danni-m 

thanks for the response. Unfortunately it doesn't sound like I'm being clear:

typically in time-series events, one needs to aggregate events to the next bar (i.e. "an event that has a raw timestamp of 11:12:01s will be counted towards 11:13"). This is used by basically *everyone* in the financial industry, and that's why it's battle-tested in pandas. The implementation in pandas is super-simple, we just use the *label* parameter

    [dataframe].resample("1min", label="right").[aggregation method]

Given the definition of ALIGN that you posted above, we have no idea how to make this work in your module. So what I'm asking for is how do I replicate the same behavior using your module. thanks!

**Comment by LiorKogan** [comment]
@vgoklani 

As @gkorland described. You can align the buckets inside the query interval either according to the start of the interval or according to the end of the interval.
Nevertheless, **the timestamp assign to each bucket is the timestamp at the start of this bucket**.
For your use case, all you have to do is add the timeBucket to the reported timestamp.

**Comment by vgoklani** [comment]
thanks @LiorKogan 

If this feature is missing, is it possible to add to the list of available options? I believe it would be very widely used. thanks!

**Comment by LiorKogan** [comment]
This is now in our roadmap.
