### ISSUE TITLE
Which docker image is best for production use?

### ISSUE THREAD

**Issue by vgoklani** [RedisTimeSeries/RedisTimeSeries#965]
Hello,

Which docker image for redistimeseries would be considered stable, such that we could use it for production.

https://hub.docker.com/r/redislabs/redistimeseries/tags

Based on the tags, it appears that *latest* is referencing v1.4 (and updated 6+ months ago), while the 1.6.x tags were updated during the last few days (edit: 1.6.0 was updated ~4 months ago)

Why is the latest referencing 1.4, is it no longer being updated? We need the ability to delete keys between time-ranges, which is possible in 1.6 but not 1.4

thanks!

**Comment by LiorKogan** [comment]
Hi @vgoklani 

Usually we add new features only to new versions, while only fixing bugs for older versions.
1.6 is expected to be released in a few days.

**Comment by vgoklani** [comment]
Hello @LiorKogan  - thanks for the response! 

Would it best then if we simply stayed on the *latest* tag; will that automatically point to v1.6 when ready?

**Comment by LiorKogan** [comment]
Yes, the _latest_ label will point to 1.6 when ready.
