### ISSUE TITLE
Block not supported rule semantic

### ISSUE THREAD

**Issue by danni-m** [RedisTimeSeries/RedisTimeSeries#97]
Currently we only allow:
Parent = Raw TS key that gets samples via TS.ADD
Child = Aggregated TS key using downsmapling rule

1. Each child can have 1 parent
2. A parent cannot have a rule that will aggregate to himself
3. A child cannot have any children
4. A parent can have multiple children

**Comment by gkorland** [comment]
It seems for 3 and 1 we need back reference to the parent @danni-m ?

**Comment by danni-m** [comment]
@gkorland yes.
